import { HudsonDesignPreset } from "@/components/site-studio/siteStudioTypes";

export const HUDSON_DESIGNS_CATALOG: HudsonDesignPreset[] = [
  {
    id: "amber-21",
    name: "Amber 21",
    category: "single-storey",
    bedrooms: 4,
    bathrooms: 2,
    cars: 2,
    totalM2: 192.2,
    widthM: 10.55,
    lengthM: 20.15,
    minLotFrontageM: 12.5,
    garageSide: "right",
    hasBtbOption: true,
    rooms: [
      { name: "PORCH", xPct: 5, yPct: 0, wPct: 40, hPct: 8 },
      { name: "GARAGE (2-CAR)", xPct: 48, yPct: 0, wPct: 52, hPct: 28 },
      { name: "MASTER BED", xPct: 0, yPct: 8, wPct: 45, hPct: 20 },
      { name: "ENSUITE / WIR", xPct: 0, yPct: 28, wPct: 45, hPct: 14 },
      { name: "ENTRY / HALL", xPct: 45, yPct: 28, wPct: 15, hPct: 22 },
      { name: "BEDROOM 2", xPct: 60, yPct: 28, wPct: 40, hPct: 16 },
      { name: "BATH / WC / LDRY", xPct: 60, yPct: 44, wPct: 40, hPct: 18 },
      { name: "BEDROOM 3", xPct: 0, yPct: 42, wPct: 45, hPct: 15 },
      { name: "BEDROOM 4", xPct: 0, yPct: 57, wPct: 45, hPct: 15 },
      { name: "KITCHEN / WIP", xPct: 55, yPct: 62, wPct: 45, hPct: 18 },
      { name: "LIVING ROOM", xPct: 0, yPct: 72, wPct: 55, hPct: 28 },
      { name: "MEALS / DINING", xPct: 55, yPct: 80, wPct: 45, hPct: 20 },
      { name: "ALFRESCO", xPct: 55, yPct: 88, wPct: 45, hPct: 12 },
    ],
  },
  {
    id: "jasper-24",
    name: "Jasper 24 (BTB Ready)",
    category: "single-storey",
    bedrooms: 4,
    bathrooms: 2,
    cars: 2,
    totalM2: 223.1,
    widthM: 10.89,
    lengthM: 21.50,
    minLotFrontageM: 12.5,
    garageSide: "right",
    hasBtbOption: true,
    rooms: [
      { name: "PORCH", xPct: 5, yPct: 0, wPct: 38, hPct: 7 },
      { name: "GARAGE (BTB 200mm)", xPct: 46, yPct: 0, wPct: 54, hPct: 28 },
      { name: "MASTER BEDROOM", xPct: 0, yPct: 7, wPct: 44, hPct: 21 },
      { name: "ENSUITE & DUAL WIR", xPct: 0, yPct: 28, wPct: 44, hPct: 14 },
      { name: "CENTRAL MEDIA / LOUNGE", xPct: 46, yPct: 28, wPct: 54, hPct: 18 },
      { name: "BEDROOM 2", xPct: 0, yPct: 42, wPct: 44, hPct: 14 },
      { name: "BEDROOM 3", xPct: 0, yPct: 56, wPct: 44, hPct: 14 },
      { name: "BATHROOM & POWDER", xPct: 46, yPct: 46, wPct: 54, hPct: 16 },
      { name: "BEDROOM 4", xPct: 0, yPct: 70, wPct: 44, hPct: 14 },
      { name: "DESIGNER KITCHEN & WIP", xPct: 46, yPct: 62, wPct: 54, hPct: 18 },
      { name: "OPEN LIVING & DINING", xPct: 0, yPct: 84, wPct: 60, hPct: 16 },
      { name: "GRAND ALFRESCO", xPct: 60, yPct: 80, wPct: 40, hPct: 20 },
    ],
  },
  {
    id: "amber-23",
    name: "Amber 23",
    category: "single-storey",
    bedrooms: 4,
    bathrooms: 2,
    cars: 2,
    totalM2: 212.5,
    widthM: 11.20,
    lengthM: 21.00,
    minLotFrontageM: 12.5,
    garageSide: "right",
    hasBtbOption: true,
    rooms: [
      { name: "PORCH", xPct: 5, yPct: 0, wPct: 40, hPct: 8 },
      { name: "GARAGE", xPct: 48, yPct: 0, wPct: 52, hPct: 27 },
      { name: "MASTER BED", xPct: 0, yPct: 8, wPct: 46, hPct: 20 },
      { name: "ENSUITE & WIR", xPct: 0, yPct: 28, wPct: 46, hPct: 14 },
      { name: "MEDIA ROOM", xPct: 48, yPct: 27, wPct: 52, hPct: 18 },
      { name: "BEDROOM 2", xPct: 0, yPct: 42, wPct: 46, hPct: 14 },
      { name: "BEDROOM 3", xPct: 0, yPct: 56, wPct: 46, hPct: 14 },
      { name: "BATHROOM & LAUNDRY", xPct: 48, yPct: 45, wPct: 52, hPct: 18 },
      { name: "KITCHEN & WIP", xPct: 48, yPct: 63, wPct: 52, hPct: 18 },
      { name: "BEDROOM 4", xPct: 0, yPct: 70, wPct: 46, hPct: 14 },
      { name: "OPEN PLAN LIVING & MEALS", xPct: 0, yPct: 84, wPct: 60, hPct: 16 },
      { name: "UNDERCOVER ALFRESCO", xPct: 60, yPct: 81, wPct: 40, hPct: 19 },
    ],
  },
  {
    id: "pearl-25",
    name: "Pearl 25 (Double Storey)",
    category: "double-storey",
    bedrooms: 4,
    bathrooms: 2.5,
    cars: 2,
    totalM2: 232.4,
    widthM: 11.50,
    lengthM: 17.80,
    minLotFrontageM: 12.5,
    garageSide: "left",
    hasBtbOption: true,
    rooms: [
      { name: "DOUBLE GARAGE", xPct: 0, yPct: 0, wPct: 50, hPct: 32 },
      { name: "PORTICO / ENTRY", xPct: 52, yPct: 0, wPct: 48, hPct: 12 },
      { name: "STUDY / MEDIA", xPct: 52, yPct: 12, wPct: 48, hPct: 20 },
      { name: "FEATURE STAIRCASE", xPct: 35, yPct: 32, wPct: 30, hPct: 18 },
      { name: "POWDER & LAUNDRY", xPct: 0, yPct: 32, wPct: 35, hPct: 18 },
      { name: "KITCHEN & BUTLER'S PANTRY", xPct: 0, yPct: 50, wPct: 50, hPct: 24 },
      { name: "MEALS / DINING", xPct: 50, yPct: 50, wPct: 50, hPct: 24 },
      { name: "FAMILY LIVING", xPct: 0, yPct: 74, wPct: 55, hPct: 26 },
      { name: "INTEGRATED ALFRESCO", xPct: 55, yPct: 74, wPct: 45, hPct: 26 },
    ],
  },
  {
    id: "mulberry-35",
    name: "Mulberry 35 (Acreage Masterpiece)",
    category: "acreage",
    bedrooms: 4,
    bathrooms: 2.5,
    cars: 3,
    totalM2: 325.4,
    widthM: 27.50,
    lengthM: 15.20,
    minLotFrontageM: 32.0,
    garageSide: "right",
    hasBtbOption: false,
    rooms: [
      { name: "TRIPLE GARAGE & WORKSHOP", xPct: 70, yPct: 0, wPct: 30, hPct: 60 },
      { name: "GRAND VERANDAH", xPct: 10, yPct: 0, wPct: 58, hPct: 15 },
      { name: "MASTER RETREAT & LUXE ENSUITE", xPct: 0, yPct: 15, wPct: 25, hPct: 60 },
      { name: "HOME THEATRE", xPct: 26, yPct: 15, wPct: 24, hPct: 35 },
      { name: "CENTRAL GOURMET KITCHEN", xPct: 51, yPct: 15, wPct: 22, hPct: 35 },
      { name: "EXPANSIVE LIVING & DINING", xPct: 26, yPct: 50, wPct: 47, hPct: 35 },
      { name: "CHILDREN'S WING (BEDS 2,3,4)", xPct: 0, yPct: 75, wPct: 45, hPct: 25 },
      { name: "PANORAMIC REAR ALFRESCO", xPct: 45, yPct: 85, wPct: 55, hPct: 15 },
    ],
  },
  {
    id: "sapphire-duplex-32",
    name: "Sapphire 32 Dual Living / Duplex",
    category: "duplex",
    bedrooms: 6,
    bathrooms: 4,
    cars: 2,
    totalM2: 298.0,
    widthM: 14.20,
    lengthM: 20.50,
    minLotFrontageM: 16.0,
    garageSide: "left",
    hasBtbOption: true,
    rooms: [
      { name: "UNIT 1 GARAGE", xPct: 0, yPct: 0, wPct: 25, hPct: 30 },
      { name: "UNIT 1 ENTRY & LIVING", xPct: 26, yPct: 0, wPct: 23, hPct: 45 },
      { name: "UNIT 2 ENTRY & LIVING", xPct: 51, yPct: 0, wPct: 23, hPct: 45 },
      { name: "UNIT 2 GARAGE", xPct: 75, yPct: 0, wPct: 25, hPct: 30 },
      { name: "UNIT 1 KITCHEN & DINING", xPct: 0, yPct: 45, wPct: 49, hPct: 25 },
      { name: "UNIT 2 KITCHEN & DINING", xPct: 51, yPct: 45, wPct: 49, hPct: 25 },
      { name: "UNIT 1 BEDS (3) & ALFRESCO", xPct: 0, yPct: 70, wPct: 49, hPct: 30 },
      { name: "UNIT 2 BEDS (3) & ALFRESCO", xPct: 51, yPct: 70, wPct: 49, hPct: 30 },
    ],
  },
];
