/* Auto-generated from the duplex / dual-occupancy design pages on
 * hudsonhomes.com.au. Each dual-occupancy design only offers the facades
 * published in its own gallery, so the library is restricted to this list. */
import type { FacadeItem } from "./facadeLibrary";

export interface DuplexFacade extends FacadeItem {
  /** Variant note printed on the design page, e.g. "Duplex (garage on inside)". */
  note: string;
  /** Sizes this facade is available on, when the page restricts it. */
  only: string;
}

export const DUPLEX_FACADES: Record<string, DuplexFacade[]> = {
  Alabaster: [
    {
      id: "alabaster-classic",
      name: "Classic",
      range: "Single Storey Duplex (garage on inside)",
      tags: ["alabaster", "classic", "duplex", "garage", "inside", "on", "single", "storey"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/03/WISTERIA-31-Classic-Facade-Dual-Occupancy-Single-Stry-1.jpg",
      note: "Single Storey Duplex (garage on inside)",
      only: "",
    },
  ],
  Cayenne: [
    {
      id: "cayenne-brixton",
      name: "Brixton",
      range: "Duplex (garage on inside)",
      tags: ["brixton", "cayenne", "duplex", "garage", "inside", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-BRIXTON-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "cayenne-bronte",
      name: "Bronte",
      range: "Duplex (garage on inside)",
      tags: ["bronte", "cayenne", "duplex", "garage", "inside", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-BRONTE-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "cayenne-classic",
      name: "Classic",
      range: "Duplex, Garage on inside",
      tags: ["cayenne", "classic", "duplex", "garage", "inside", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/10/MAIZE-Classic-Facade-Duplex-2-Stry-AMENDED.jpg",
      note: "Duplex, Garage on inside",
      only: "",
    },
    {
      id: "cayenne-classic-plus",
      name: "Classic Plus",
      range: "Duplex (garage on inside)",
      tags: ["cayenne", "classic", "duplex", "garage", "inside", "on", "plus"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/07/Hudson-Homes-Duplex-Experts-Australias-Best-Home-Builder-MAIZE-Classic-Plus-Facade-Duplex-2-Stry-1.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "cayenne-cranbrook",
      name: "Cranbrook",
      range: "Duplex (garage on inside)",
      tags: ["cayenne", "cranbrook", "duplex", "garage", "inside", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-CRANBROOK-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "cayenne-mayfield",
      name: "Mayfield",
      range: "Duplex (garage on inside)",
      tags: ["cayenne", "duplex", "garage", "inside", "mayfield", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-MAYFIELD-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "cayenne-madison",
      name: "Madison",
      range: "Duplex, Garage on inside",
      tags: ["cayenne", "duplex", "garage", "inside", "madison", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAIZE-A-or-B-Madison-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on inside",
      only: "",
    },
    {
      id: "cayenne-marina",
      name: "Marina",
      range: "Duplex, Garage on Inside",
      tags: ["cayenne", "duplex", "garage", "inside", "marina", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAIZE-A-or-B-Marina-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on Inside",
      only: "",
    },
    {
      id: "cayenne-modena",
      name: "Modena",
      range: "Duplex (garage on inside)",
      tags: ["cayenne", "duplex", "garage", "inside", "modena", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-MODENA-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "cayenne-vista",
      name: "Vista",
      range: "Duplex, Garage on inside",
      tags: ["cayenne", "duplex", "garage", "inside", "on", "vista"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAIZE-A-or-B-Vista-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on inside",
      only: "",
    },
    {
      id: "cayenne-woodlands",
      name: "Woodlands",
      range: "Duplex (garage on inside)",
      tags: ["cayenne", "duplex", "garage", "inside", "on", "woodlands"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-WOODLANDS-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
  ],
  Teal: [
    {
      id: "teal-classic",
      name: "Classic",
      range: "Duplex, Corner Block Design",
      tags: ["block", "classic", "corner", "design", "duplex", "teal"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/07/TEAL-Classic-Facade-Duplex-Corner-2-Stry.jpg",
      note: "Duplex, Corner Block Design",
      only: "",
    },
    {
      id: "teal-classic-plus",
      name: "Classic Plus",
      range: "Duplex (corner block)",
      tags: ["block", "classic", "corner", "duplex", "plus", "teal"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/09/TEAL-Classic-Plus-Facade-Duplex-Corner-2-Stry.jpg",
      note: "Duplex (corner block)",
      only: "",
    },
    {
      id: "teal-madison",
      name: "Madison",
      range: "Duplex, Corner Block",
      tags: ["block", "corner", "duplex", "madison", "teal"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/07/TEAL-Madison-Facade-Duplex-Corner-2-Stry.jpg",
      note: "Duplex, Corner Block",
      only: "",
    },
  ],
  Wisteria: [
    {
      id: "wisteria-classic-plus",
      name: "Classic Plus",
      range: "Dual Occupancy (double garage)",
      tags: ["classic", "double", "dual", "garage", "occupancy", "plus", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/07/Hudson-Homes-Dual-Living-Experts-Award-Winning-WISTERIA-24-Classic-Plus-Facade-Dual-Occupancy-Single-Stry.jpg",
      note: "Dual Occupancy (double garage)",
      only: "",
    },
    {
      id: "wisteria-aspen",
      name: "Aspen",
      range: "Single Storey (double garage)",
      tags: ["aspen", "double", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Aspen-Facade-Single-Storey.jpg",
      note: "Single Storey (double garage)",
      only: "",
    },
    {
      id: "wisteria-avalon",
      name: "Avalon",
      range: "Single Storey (double garage)",
      tags: ["avalon", "double", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Avalon-Facade-Single-Storey.jpg",
      note: "Single Storey (double garage)",
      only: "28, 29 and 31 only",
    },
    {
      id: "wisteria-avoca",
      name: "Avoca",
      range: "Dual Occupancy (double garage)",
      tags: ["avoca", "double", "dual", "garage", "occupancy", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/WISTERIA-Avoca-Facade-Dual-Occupancy-Single-Stry.jpg",
      note: "Dual Occupancy (double garage)",
      only: "",
    },
    {
      id: "wisteria-banksia",
      name: "Banksia",
      range: "Single Storey (double garage)",
      tags: ["banksia", "double", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Banksia-Facade-Single-Storey.jpg",
      note: "Single Storey (double garage)",
      only: "",
    },
    {
      id: "wisteria-bayside",
      name: "Bayside",
      range: "Single Storey (double garage)",
      tags: ["bayside", "double", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Bayside-Facade-Single-Storey.jpg",
      note: "Single Storey (double garage)",
      only: "",
    },
    {
      id: "wisteria-breeze",
      name: "Breeze",
      range: "Single Storey (single garage)",
      tags: ["breeze", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Breeze-Facade-Single-Storey.jpg",
      note: "Single Storey (single garage)",
      only: "",
    },
    {
      id: "wisteria-classic",
      name: "Classic",
      range: "Dual Occupancy, Double Garage",
      tags: ["classic", "double", "dual", "garage", "occupancy", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/WISTERIA-Classic-Facade-Dual-Occupancy-Single-Stry.jpg",
      note: "Dual Occupancy, Double Garage",
      only: "",
    },
    {
      id: "wisteria-classic",
      name: "Classic",
      range: "Single Storey Duplex (garage on inside)",
      tags: ["classic", "duplex", "garage", "inside", "on", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/03/WISTERIA-31-Classic-Facade-Dual-Occupancy-Single-Stry-1.jpg",
      note: "Single Storey Duplex (garage on inside)",
      only: "31 only",
    },
    {
      id: "wisteria-classic-plus",
      name: "Classic Plus",
      range: "Single Storey, Double Garage",
      tags: ["classic", "double", "garage", "plus", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/01/CLASSIC-PLUS-SINGLE-STOREY-1.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-classic-plus",
      name: "Classic Plus",
      range: "Double Storey, Double Garage",
      tags: ["classic", "double", "garage", "plus", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/01/Classic-Plus-Facade-Double-Garage-2-Stry.jpg",
      note: "Double Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-coastal",
      name: "Coastal",
      range: "Single Storey, Double Garage",
      tags: ["coastal", "double", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Coastal-Facade-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-contemporary",
      name: "Contemporary",
      range: "Single Storey, Double Garage",
      tags: ["contemporary", "double", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Contemporary-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-crest",
      name: "Crest",
      range: "Dual Occupancy, Double Garage",
      tags: ["crest", "double", "dual", "garage", "occupancy", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/WISTERIA-Crest-Facade-Dual-Occupancy-Single-Stry.jpg",
      note: "Dual Occupancy, Double Garage",
      only: "",
    },
    {
      id: "wisteria-eden",
      name: "Eden",
      range: "Single Storey, Double Garage",
      tags: ["double", "eden", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Eden-Facade-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-elite",
      name: "Elite",
      range: "Single Storey, Double Garage",
      tags: ["double", "elite", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Elite-Facade-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-executive",
      name: "Executive",
      range: "Single Storey, Double Garage",
      tags: ["double", "executive", "garage", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Executive-Facade-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-harmony",
      name: "Harmony",
      range: "dual Occupancy, Double Garage",
      tags: ["double", "dual", "garage", "harmony", "occupancy", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/WISTERIA-Harmony-Facade-Dual-Occupancy-Single-Stry.jpg",
      note: "dual Occupancy, Double Garage",
      only: "",
    },
    {
      id: "wisteria-hillsdale",
      name: "Hillsdale",
      range: "Single Storey, Double Garage",
      tags: ["double", "garage", "hillsdale", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Hillsdale-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-infinity",
      name: "Infinity",
      range: "Single Storey, Double Garage",
      tags: ["double", "garage", "infinity", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Infinity-MKii-Facade-Single-Storey-1.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-majestic",
      name: "Majestic",
      range: "Single Storey, Double Garage",
      tags: ["double", "garage", "majestic", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Majestic-Facade-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-pavilion",
      name: "Pavilion",
      range: "Single Storey, Double Garage",
      tags: ["double", "garage", "pavilion", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Pavillion-Facade-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-riviera",
      name: "Riviera",
      range: "Single Storey, Double Garage",
      tags: ["double", "garage", "riviera", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Riviera-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-savoy",
      name: "Savoy",
      range: "Single Storey, Double Garage",
      tags: ["double", "garage", "savoy", "single", "storey", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Savoy-Facade-Single-Storey.jpg",
      note: "Single Storey, Double Garage",
      only: "",
    },
    {
      id: "wisteria-serenity",
      name: "Serenity",
      range: "Dual Occupancy, Double Garage",
      tags: ["double", "dual", "garage", "occupancy", "serenity", "wisteria"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/WISTERIA-Serenity-Facade-Dual-Occupancy-Single-Stry.jpg",
      note: "Dual Occupancy, Double Garage",
      only: "",
    },
  ],
  Magnolia: [
    {
      id: "magnolia-classic",
      name: "Classic",
      range: "Duplex (garage on outside) 2026 Magnolia",
      tags: ["2026", "classic", "duplex", "garage", "magnolia", "on", "outside"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2026/02/MAGNOLIA-Classic-Facade-Duplex-2-Stry-AMENDED.jpg",
      note: "Duplex (garage on outside) 2026 Magnolia",
      only: "",
    },
    {
      id: "magnolia-classic-plus",
      name: "Classic Plus",
      range: "Duplex (garage on outside)",
      tags: ["classic", "duplex", "garage", "magnolia", "on", "outside", "plus"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/07/Hudson-Homes-Duplex-Experts-MAGNOLIA-Classic-Plus-Facade-Duplex-2-Stry.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "magnolia-madison",
      name: "Madison",
      range: "Duplex, garage on outside",
      tags: ["duplex", "garage", "madison", "magnolia", "on", "outside"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAGNOLIA-Madison-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, garage on outside",
      only: "",
    },
    {
      id: "magnolia-vista",
      name: "Vista",
      range: "Duplex, garage on outside",
      tags: ["duplex", "garage", "magnolia", "on", "outside", "vista"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAGNOLIA-Vista-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, garage on outside",
      only: "",
    },
    {
      id: "magnolia-marina",
      name: "Marina",
      range: "Duplex, Garage on outside",
      tags: ["duplex", "garage", "magnolia", "marina", "on", "outside"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAGNOLIA-Marina-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on outside",
      only: "",
    },
    {
      id: "magnolia-woodlands",
      name: "Woodlands",
      range: "Duplex (garage on outside)",
      tags: ["duplex", "garage", "magnolia", "on", "outside", "woodlands"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-WOODLANDS-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "magnolia-modena",
      name: "Modena",
      range: "Duplex (garage on outside)",
      tags: ["duplex", "garage", "magnolia", "modena", "on", "outside"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-MODENA-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "magnolia-mayfield",
      name: "Mayfield",
      range: "Duplex (garage on outside)",
      tags: ["duplex", "garage", "magnolia", "mayfield", "on", "outside"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-MAYFIELD-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "magnolia-cranbrook",
      name: "Cranbrook",
      range: "Duplex (garage on outside)",
      tags: ["cranbrook", "duplex", "garage", "magnolia", "on", "outside"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-CRANBROOK-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "magnolia-brixton",
      name: "Brixton",
      range: "Duplex (garage on outside)",
      tags: ["brixton", "duplex", "garage", "magnolia", "on", "outside"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-BRIXTON-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "magnolia-bronte",
      name: "Bronte",
      range: "Duplex (garage on outside)",
      tags: ["bronte", "duplex", "garage", "magnolia", "on", "outside"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-BRONTE-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
  ],
  Maize: [
    {
      id: "maize-classic",
      name: "Classic",
      range: "Duplex (garage on inside) 2026 Maize",
      tags: ["2026", "classic", "duplex", "garage", "inside", "maize", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2026/02/MAIZE-Classic-Facade-Duplex-2-Stry-AMENDED.jpg",
      note: "Duplex (garage on inside) 2026 Maize",
      only: "",
    },
    {
      id: "maize-classic-plus",
      name: "Classic Plus",
      range: "Duplex (garage on inside)",
      tags: ["classic", "duplex", "garage", "inside", "maize", "on", "plus"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/07/Hudson-Homes-Duplex-Experts-Australias-Best-Home-Builder-MAIZE-Classic-Plus-Facade-Duplex-2-Stry-1.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "maize-madison",
      name: "Madison",
      range: "Duplex, Garage on inside",
      tags: ["duplex", "garage", "inside", "madison", "maize", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAIZE-A-or-B-Madison-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on inside",
      only: "",
    },
    {
      id: "maize-marina",
      name: "Marina",
      range: "Duplex, Garage on Inside",
      tags: ["duplex", "garage", "inside", "maize", "marina", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAIZE-A-or-B-Marina-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on Inside",
      only: "",
    },
    {
      id: "maize-vista",
      name: "Vista",
      range: "Duplex, Garage on inside",
      tags: ["duplex", "garage", "inside", "maize", "on", "vista"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAIZE-A-or-B-Vista-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on inside",
      only: "",
    },
    {
      id: "maize-brixton",
      name: "Brixton",
      range: "Duplex (garage on inside)",
      tags: ["brixton", "duplex", "garage", "inside", "maize", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-BRIXTON-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "maize-bronte",
      name: "Bronte",
      range: "Duplex (garage on inside)",
      tags: ["bronte", "duplex", "garage", "inside", "maize", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-BRONTE-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "maize-cranbrook",
      name: "Cranbrook",
      range: "Duplex (garage on inside)",
      tags: ["cranbrook", "duplex", "garage", "inside", "maize", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-CRANBROOK-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "maize-mayfield",
      name: "Mayfield",
      range: "Duplex (garage on inside)",
      tags: ["duplex", "garage", "inside", "maize", "mayfield", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-MAYFIELD-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "maize-modena",
      name: "Modena",
      range: "Duplex (garage on inside)",
      tags: ["duplex", "garage", "inside", "maize", "modena", "on"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-MODENA-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
    {
      id: "maize-woodlands",
      name: "Woodlands",
      range: "Duplex (garage on inside)",
      tags: ["duplex", "garage", "inside", "maize", "on", "woodlands"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAIZE-WOODLANDS-FACADE.jpg",
      note: "Duplex (garage on inside)",
      only: "",
    },
  ],
  Raven: [
    {
      id: "raven-brixton",
      name: "Brixton",
      range: "Duplex (garage on outside)",
      tags: ["brixton", "duplex", "garage", "on", "outside", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-BRIXTON-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "raven-bronte",
      name: "Bronte",
      range: "Duplex (garage on outside)",
      tags: ["bronte", "duplex", "garage", "on", "outside", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-BRONTE-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "raven-cranbrook",
      name: "Cranbrook",
      range: "Duplex (garage on outside)",
      tags: ["cranbrook", "duplex", "garage", "on", "outside", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-CRANBROOK-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "raven-classic",
      name: "Classic",
      range: "Duplex, Garage on outside",
      tags: ["classic", "duplex", "garage", "on", "outside", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAGNOLIA-Classic-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on outside",
      only: "",
    },
    {
      id: "raven-classic-plus",
      name: "Classic Plus",
      range: "Duplex (garage on outside)",
      tags: ["classic", "duplex", "garage", "on", "outside", "plus", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/07/Hudson-Homes-Duplex-Experts-MAGNOLIA-Classic-Plus-Facade-Duplex-2-Stry.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "raven-madison",
      name: "Madison",
      range: "Duplex, garage on outside",
      tags: ["duplex", "garage", "madison", "on", "outside", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAGNOLIA-Madison-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, garage on outside",
      only: "",
    },
    {
      id: "raven-marina",
      name: "Marina",
      range: "Duplex, Garage on outside",
      tags: ["duplex", "garage", "marina", "on", "outside", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAGNOLIA-Marina-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, Garage on outside",
      only: "",
    },
    {
      id: "raven-mayfield",
      name: "Mayfield",
      range: "Duplex (garage on outside)",
      tags: ["duplex", "garage", "mayfield", "on", "outside", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-MAYFIELD-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "raven-modena",
      name: "Modena",
      range: "Duplex (garage on outside)",
      tags: ["duplex", "garage", "modena", "on", "outside", "raven"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-MODENA-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
    {
      id: "raven-vista",
      name: "Vista",
      range: "Duplex, garage on outside",
      tags: ["duplex", "garage", "on", "outside", "raven", "vista"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MAGNOLIA-Vista-Facade-Duplex-2-Stry.jpg",
      note: "Duplex, garage on outside",
      only: "",
    },
    {
      id: "raven-woodlands",
      name: "Woodlands",
      range: "Duplex (garage on outside)",
      tags: ["duplex", "garage", "on", "outside", "raven", "woodlands"],
      url: "https://www.hudsonhomes.com.au/wp-content/uploads/2025/04/MAGNOLIA-WOODLANDS-FACADE.jpg",
      note: "Duplex (garage on outside)",
      only: "",
    },
  ],
};

/** Price-list spellings that differ from the website's design family names. */
const FAMILY_ALIASES: Record<string, string> = {
  cayene: "Cayenne",
  cayenne: "Cayenne",
  pavillion: "Pavilion",
};

/** Designs drawn as two dwellings each with their own single garage on the
 *  inside — only the dual-occupancy / duplex renders suit them, never the
 *  standard single-dwelling facades. */
const TWO_SINGLE_GARAGE_FAMILIES: Record<string, string> = {
  Wisteria: "Wisteria",
};

/** The extra Wisteria duplex renders are only offered up to 28 squares —
 *  larger Wisteria plans (and the Alabaster) only take the Classic facade. */
const WISTERIA_EXTRA_FACADE_MAX_SIZE = 28;

function isDualOccupancyRender(f: DuplexFacade): boolean {
  return /dual\s*occupancy|duplex/i.test(`${f.note} ${f.range}`);
}

function slug(value: string): string {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

/** The duplex facades published for a dual-occupancy design name, e.g. "Maize 43". */
export function duplexFacadesForDesign(designName: string): DuplexFacade[] {
  const family = designName.trim().split(/[^A-Za-z]/)[0].toLowerCase();
  const key =
    FAMILY_ALIASES[family] ?? Object.keys(DUPLEX_FACADES).find((k) => k.toLowerCase() === family);
  if (!key) return [];

  const source = TWO_SINGLE_GARAGE_FAMILIES[key];
  if (source) {
    const size = Number(designName.replace(/[^0-9.]/g, ""));
    const classicOnly = Number.isFinite(size) && size > WISTERIA_EXTRA_FACADE_MAX_SIZE;
    const seen = new Set<string>();
    return (DUPLEX_FACADES[source] ?? [])
      .filter(isDualOccupancyRender)
      .filter((f) => !classicOnly || /^classic$/i.test(f.name))
      .filter((f) => (seen.has(f.url) ? false : (seen.add(f.url), true)))
      .map((f, i) => ({ ...f, id: `${key.toLowerCase()}-${slug(f.name)}-${i}` }));
  }

  return DUPLEX_FACADES[key] ?? [];
}

