/* Auto-generated from the hudsonhomes.com.au facade galleries. */
import type { FacadeItem } from "./facadeLibrary";

export const HUDSON_FACADES: FacadeItem[] = [
  {
    id: "allure",
    name: "Allure",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["allure", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Allure-Facade-2-Stry.jpg",
  },
  {
    id: "ascot",
    name: "Ascot",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["ascot", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Ascot-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "ashton",
    name: "Ashton",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["ashton", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Ashton-Facade-2-Stry.jpg",
  },
  {
    id: "aspen",
    name: "Aspen",
    range: "Single Storey / Double Storey / Narrow Lot / Split Level / Duplex",
    tags: ["aspen", "double", "duplex", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Aspen-Facade-Single-Storey.jpg",
  },
  {
    id: "aspen-single-garage",
    name: "Aspen (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["aspen", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Aspen-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "avalon",
    name: "Avalon",
    range: "Single Storey / Narrow Lot / Duplex",
    tags: ["avalon", "duplex", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Avalon-Facade-Single-Storey.jpg",
  },
  {
    id: "avoca",
    name: "Avoca",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["avoca", "duplex", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Avoca-Facade-Single-Storey.jpg",
  },
  {
    id: "avoca-single-garage",
    name: "Avoca (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["avoca", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Avoca-Facade-Single-Storey-single-garage-scaled.jpg",
  },
  {
    id: "banksia",
    name: "Banksia",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["banksia", "duplex", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Banksia-Facade-Single-Storey.jpg",
  },
  {
    id: "banksia-single-garage",
    name: "Banksia (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["banksia", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Banksia-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "bayside",
    name: "Bayside",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["bayside", "duplex", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Bayside-Facade-Single-Storey.jpg",
  },
  {
    id: "bayside-single-garage",
    name: "Bayside (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["bayside", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Bayside-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "breeze",
    name: "Breeze",
    range: "Single Storey / Double Storey / Narrow Lot / Split Level / Duplex",
    tags: ["breeze", "double", "duplex", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Breeze-Facade-Single-Storey.jpg",
  },
  {
    id: "breeze-single-garage",
    name: "Breeze (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["breeze", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Breeze-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "cambridge",
    name: "Cambridge",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["cambridge", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Cambridge-Facade-2-Stry.jpg",
  },
  {
    id: "centro",
    name: "Centro",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["centro", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Centro-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "chateaux",
    name: "Chateaux",
    range: "Single Storey / Double Storey / Narrow Lot / Split Level",
    tags: ["chateaux", "double", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Chateaux-Facade-Single-Storey.jpg",
  },
  {
    id: "chateaux-single-garage",
    name: "Chateaux (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["chateaux", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Chateaux-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "classic",
    name: "Classic",
    range: "Single Storey / Narrow Lot / Split Level / Acreage / Duplex",
    tags: ["acreage", "classic", "duplex", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Classic-Facade-Single-Stry.jpg",
  },
  {
    id: "classic-double-garage",
    name: "Classic (Double Garage)",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["classic", "double", "garage", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Classic-Facade-Double-Garage-2-Stry.jpg",
  },
  {
    id: "classic-single-garage",
    name: "Classic (Single Garage)",
    range: "Single Storey / Double Storey / Narrow Lot",
    tags: ["classic", "double", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Classic-Facade-Narrow-Single-Garage-Single-Stry.jpg",
  },
  {
    id: "classic-plus",
    name: "Classic Plus",
    range: "Narrow Lot / Acreage / Duplex",
    tags: ["acreage", "classic", "duplex", "lot", "narrow", "plus"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/07/Hudson-Homes-Dual-Living-Experts-Award-Winning-WISTERIA-24-Classic-Plus-Facade-Dual-Occupancy-Single-Stry.jpg",
  },
  {
    id: "classic-plus-double-garage",
    name: "Classic Plus (Double Garage)",
    range: "Double Storey / Narrow Lot / Split Level / Duplex",
    tags: [
      "classic",
      "double",
      "duplex",
      "garage",
      "level",
      "lot",
      "narrow",
      "plus",
      "split",
      "storey",
    ],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/01/Classic-Plus-Facade-Double-Garage-2-Stry.jpg",
  },
  {
    id: "coastal",
    name: "Coastal",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["coastal", "duplex", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Coastal-Facade-Single-Storey.jpg",
  },
  {
    id: "coastal-single-garage",
    name: "Coastal (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["coastal", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Coastal-Facade-Single-storey-single-garage.jpg",
  },
  {
    id: "como",
    name: "Como",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["como", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Como-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "contemporary",
    name: "Contemporary",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["contemporary", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Contemporary-Facade-2-Stry.jpg",
  },
  {
    id: "contemporary-single-garage",
    name: "Contemporary (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["contemporary", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Contemporary-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "crest",
    name: "Crest",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["crest", "duplex", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Crest-Facade-Single-Storey.jpg",
  },
  {
    id: "crest-single-garage",
    name: "Crest (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["crest", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Crest-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "deco-double-garage",
    name: "Deco (Double Garage)",
    range: "Double Storey / Narrow Lot",
    tags: ["deco", "double", "garage", "lot", "narrow", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Deco-Facade-Double-Garage2-Stry.jpg",
  },
  {
    id: "deco-single-garage",
    name: "Deco (Single Garage)",
    range: "Double Storey / Narrow Lot",
    tags: ["deco", "double", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Deco-Facade-Single-Garage2-Stry.jpg",
  },
  {
    id: "delta",
    name: "Delta",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["delta", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Delta-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "deluxe",
    name: "Deluxe",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["deluxe", "double", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Deluxe-Facade-2-Stry.jpg",
  },
  {
    id: "eden",
    name: "Eden",
    range: "Single Storey / Narrow Lot / Split Level / Acreage / Duplex",
    tags: ["acreage", "duplex", "eden", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Eden-Facade-Single-Storey.jpg",
  },
  {
    id: "eden-single-garage",
    name: "Eden (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["eden", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Eden-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "elite",
    name: "Elite",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["duplex", "elite", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Elite-Facade-Single-Storey.jpg",
  },
  {
    id: "elite-single-garage",
    name: "Elite (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["elite", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Elite-Facade-Single-storey-single-garage.jpg",
  },
  {
    id: "executive",
    name: "Executive",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["duplex", "executive", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Executive-Facade-Single-Storey.jpg",
  },
  {
    id: "executive-single-garage",
    name: "Executive (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["executive", "garage", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Executive-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "flair",
    name: "Flair",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "flair", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Flair-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "grande",
    name: "Grande",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "grande", "level", "lot", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Grande-Facade-2-Stry.jpg",
  },
  {
    id: "hamptons",
    name: "Hamptons",
    range: "Narrow Lot / Split Level / Acreage",
    tags: ["acreage", "hamptons", "level", "lot", "narrow", "split"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/10/Hamptons-Facade-Split-Level-Cobalt.jpg",
  },
  {
    id: "harmony",
    name: "Harmony",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["duplex", "harmony", "level", "lot", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Harmony-Facade-Single-Storey.jpg",
  },
  {
    id: "harmony-single-garage",
    name: "Harmony (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "harmony", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Harmony-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "havana",
    name: "Havana",
    range: "Single Storey / Narrow Lot",
    tags: ["havana", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Havana-Facade-Single-Storey.jpg",
  },
  {
    id: "hillsdale-single-garage",
    name: "Hillsdale (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "hillsdale", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Hillsdale-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "imperial",
    name: "Imperial",
    range: "Single Storey / Narrow Lot / Acreage",
    tags: ["acreage", "imperial", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Imperial-Facade-Single-Storey.jpg",
  },
  {
    id: "infinity",
    name: "Infinity",
    range: "Narrow Lot / Split Level",
    tags: ["infinity", "level", "lot", "narrow", "split"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/10/Infinity-Facade-Split-Level-Cobalt.jpg",
  },
  {
    id: "infinity-single-garage",
    name: "Infinity (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "infinity", "lot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Infinity-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "infinity-mkii",
    name: "Infinity MKii",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["duplex", "infinity", "level", "lot", "mkii", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Infinity-MKii-Facade-Single-Storey-1-scaled.jpg",
  },
  {
    id: "madison",
    name: "Madison",
    range: "Double Storey / Narrow Lot / Duplex",
    tags: ["double", "duplex", "lot", "madison", "narrow", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Madison-Facade-2-Stry.jpg",
  },
  {
    id: "majestic",
    name: "Majestic",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["duplex", "level", "lot", "majestic", "narrow", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Majestic-Facade-Single-Storey.jpg",
  },
  {
    id: "majestic-double-garage",
    name: "Majestic (Double Garage)",
    range: "Double Storey / Narrow Lot",
    tags: ["double", "garage", "lot", "majestic", "narrow", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Majestic-Facade-Double-Garage2-Stry.jpg",
  },
  {
    id: "majestic-single-garage",
    name: "Majestic (Single Garage)",
    range: "Single Storey / Double Storey / Narrow Lot",
    tags: ["double", "garage", "lot", "majestic", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Majestic-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "mantra-double-garage",
    name: "Mantra (Double Garage)",
    range: "Double Storey / Narrow Lot",
    tags: ["double", "garage", "lot", "mantra", "narrow", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mantra-Facade-Double-Garage2-Stry.jpg",
  },
  {
    id: "mantra-single-garage",
    name: "Mantra (Single Garage)",
    range: "Double Storey / Narrow Lot",
    tags: ["double", "garage", "lot", "mantra", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mantra-Facade-Single-Garage2-Stry.jpg",
  },
  {
    id: "marina",
    name: "Marina",
    range: "Double Storey / Narrow Lot / Split Level / Duplex",
    tags: ["double", "duplex", "level", "lot", "marina", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Marina-Facade-2-Stry.jpg",
  },
  {
    id: "meridian",
    name: "Meridian",
    range: "Double Storey / Narrow Lot",
    tags: ["double", "lot", "meridian", "narrow", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Meridian-Facade-2-Stry.jpg",
  },
  {
    id: "merlot",
    name: "Merlot",
    range: "Single Storey / Narrow Lot",
    tags: ["lot", "merlot", "narrow", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Merlot-Facade-Single-Storey.jpg",
  },
  {
    id: "metro",
    name: "Metro",
    range: "Narrow Lot / Acreage",
    tags: ["acreage", "lot", "metro", "narrow"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MULBERRY-Metro-Facade-Single-Storey-Statesman.jpg",
  },
  {
    id: "monash",
    name: "Monash",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "monash", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Monash-Facade-2-Stry.jpg",
  },
  {
    id: "mondo",
    name: "Mondo",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "mondo", "narrow", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mondo-Facade-2-Stry.jpg",
  },
  {
    id: "newport",
    name: "Newport",
    range: "Single Storey / Narrow Lot",
    tags: ["lot", "narrow", "newport", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Newport-Facade-Single-Storey.jpg",
  },
  {
    id: "novare",
    name: "Novare",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "novare", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Novare-Facade-2-Stry.jpg",
  },
  {
    id: "nuvo",
    name: "Nuvo",
    range: "Single Storey / Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "nuvo", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Nuvo-Facade-Single-Storey.jpg",
  },
  {
    id: "oxford",
    name: "Oxford",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "oxford", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Oxford-Facade-2-Stry.jpg",
  },
  {
    id: "pavillion",
    name: "Pavillion",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["duplex", "level", "lot", "narrow", "pavillion", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Pavillion-Facade-Single-Storey.jpg",
  },
  {
    id: "pavillion-single-garage",
    name: "Pavillion (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "lot", "narrow", "pavillion", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Pavillion-Facade-Single-storey-single-garage.jpg",
  },
  {
    id: "regal",
    name: "Regal",
    range: "Single Storey / Narrow Lot",
    tags: ["lot", "narrow", "regal", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Regal-Facade-Single-Storey.jpg",
  },
  {
    id: "riviera",
    name: "Riviera",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "riviera", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Riviera-Facade-2-Stry-old.jpg",
  },
  {
    id: "riviera-single-garage",
    name: "Riviera (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "lot", "narrow", "riviera", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Riviera-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "royale",
    name: "Royale",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "royale", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Royale-Facade-2-Stry-amended.jpg",
  },
  {
    id: "saville",
    name: "Saville",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "saville", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Saville-Facade-2-Stry-amended.jpg",
  },
  {
    id: "savoy",
    name: "Savoy",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["duplex", "level", "lot", "narrow", "savoy", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Savoy-Facade-Single-Storey.jpg",
  },
  {
    id: "savoy-single-garage",
    name: "Savoy (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "lot", "narrow", "savoy", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Savoy-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "serenity",
    name: "Serenity",
    range: "Single Storey / Narrow Lot / Split Level / Duplex",
    tags: ["duplex", "level", "lot", "narrow", "serenity", "single", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Serenity-Facade-Single-Storey.jpg",
  },
  {
    id: "serenity-single-garage",
    name: "Serenity (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "lot", "narrow", "serenity", "single", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Serenity-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "sierra",
    name: "Sierra",
    range: "Double Storey / Narrow Lot",
    tags: ["double", "lot", "narrow", "sierra", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Sierra-Facade-2-Stry.jpg",
  },
  {
    id: "soho",
    name: "Soho",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "soho", "split", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Soho-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "sovereign",
    name: "Sovereign",
    range: "Single Storey / Narrow Lot",
    tags: ["lot", "narrow", "single", "sovereign", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Sovereign-Facade-Single-Storey.jpg",
  },
  {
    id: "sovereign-single-garage",
    name: "Sovereign (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "lot", "narrow", "single", "sovereign", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Sovereign-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "statesman",
    name: "Statesman",
    range: "Single Storey / Double Storey / Narrow Lot / Split Level / Acreage",
    tags: ["acreage", "double", "level", "lot", "narrow", "single", "split", "statesman", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Statesman-Facade-Single-Storey.jpg",
  },
  {
    id: "statesman-single-garage",
    name: "Statesman (Single Garage)",
    range: "Single Storey / Narrow Lot",
    tags: ["garage", "lot", "narrow", "single", "statesman", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Statesman-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "tempo",
    name: "Tempo",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "split", "storey", "tempo"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Tempo-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "urban",
    name: "Urban",
    range: "Narrow Lot / Acreage",
    tags: ["acreage", "lot", "narrow", "urban"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MULBERRY-Urban-Facade-Single-Storey-Statesman.jpg",
  },
  {
    id: "vibe",
    name: "Vibe",
    range: "Single Storey / Narrow Lot",
    tags: ["lot", "narrow", "single", "storey", "vibe"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Vibe-Facade-Single-Storey.jpg",
  },
  {
    id: "vienna",
    name: "Vienna",
    range: "Single Storey / Narrow Lot",
    tags: ["lot", "narrow", "single", "storey", "vienna"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Vienna-Facade-Single-Storey.jpg",
  },
  {
    id: "visage",
    name: "Visage",
    range: "Single Storey / Narrow Lot",
    tags: ["lot", "narrow", "single", "storey", "visage"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Visage-Facade-Single-Storey.jpg",
  },
  {
    id: "vista",
    name: "Vista",
    range: "Double Storey / Narrow Lot / Split Level / Duplex",
    tags: ["double", "duplex", "level", "lot", "narrow", "split", "storey", "vista"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Vista-Facade-2-Stry.jpg",
  },
  {
    id: "vogue",
    name: "Vogue",
    range: "Single Storey / Narrow Lot / Split Level / Acreage",
    tags: ["acreage", "level", "lot", "narrow", "single", "split", "storey", "vogue"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Vogue-Facade-Single-Storey.jpg",
  },
  {
    id: "windsor",
    name: "Windsor",
    range: "Double Storey / Narrow Lot / Split Level",
    tags: ["double", "level", "lot", "narrow", "split", "storey", "windsor"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Windsor-Facade-2-Stry.jpg",
  },
];
