/* Auto-generated from the hudsonhomes.com.au facade galleries. */
import type { FacadeItem } from "./facadeLibrary";

export const HUDSON_FACADES: FacadeItem[] = [
  {
    id: "allure",
    name: "Allure",
    range: "Double Storey",
    tags: ["allure", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Allure-Facade-2-Stry.jpg",
  },
  {
    id: "ascot",
    name: "Ascot",
    range: "Double Storey",
    tags: ["ascot", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Ascot-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "ashton",
    name: "Ashton",
    range: "Double Storey",
    tags: ["ashton", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Ashton-Facade-2-Stry.jpg",
  },
  {
    id: "aspen",
    name: "Aspen",
    range: "Single Storey",
    tags: ["aspen", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Aspen-Facade-Single-Storey.jpg",
  },
  {
    id: "aspen-single-garage",
    name: "Aspen (Single Garage)",
    range: "Single Storey",
    tags: ["aspen", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Aspen-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "avalon",
    name: "Avalon",
    range: "Single Storey",
    tags: ["avalon", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Avalon-Facade-Single-Storey.jpg",
  },
  {
    id: "avoca",
    name: "Avoca",
    range: "Single Storey",
    tags: ["avoca", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Avoca-Facade-Single-Storey.jpg",
  },
  {
    id: "avoca-single-garage",
    name: "Avoca (Single Garage)",
    range: "Single Storey",
    tags: ["avoca", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Avoca-Facade-Single-Storey-single-garage-scaled.jpg",
  },
  {
    id: "banksia",
    name: "Banksia",
    range: "Single Storey",
    tags: ["banksia", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Banksia-Facade-Single-Storey.jpg",
  },
  {
    id: "banksia-single-garage",
    name: "Banksia (Single Garage)",
    range: "Single Storey",
    tags: ["banksia", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Banksia-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "bayside",
    name: "Bayside",
    range: "Single Storey",
    tags: ["bayside", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Bayside-Facade-Single-Storey.jpg",
  },
  {
    id: "bayside-single-garage",
    name: "Bayside (Single Garage)",
    range: "Single Storey",
    tags: ["bayside", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Bayside-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "breeze",
    name: "Breeze",
    range: "Single Storey",
    tags: ["breeze", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Breeze-Facade-Single-Storey.jpg",
  },
  {
    id: "breeze-single-garage",
    name: "Breeze (Single Garage)",
    range: "Single Storey",
    tags: ["breeze", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Breeze-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "cambridge",
    name: "Cambridge",
    range: "Double Storey",
    tags: ["cambridge", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Cambridge-Facade-2-Stry.jpg",
  },
  {
    id: "centro",
    name: "Centro",
    range: "Double Storey",
    tags: ["centro", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Centro-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "chateaux",
    name: "Chateaux",
    range: "Single Storey",
    tags: ["chateaux", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Chateaux-Facade-Single-Storey.jpg",
  },
  {
    id: "chateaux-single-garage",
    name: "Chateaux (Single Garage)",
    range: "Single Storey",
    tags: ["chateaux", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Chateaux-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "classic",
    name: "Classic",
    range: "Single Storey",
    tags: ["classic", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Classic-Facade-Single-Stry.jpg",
  },
  {
    id: "classic-double-garage",
    name: "Classic (Double Storey)",
    range: "Double Storey",
    tags: ["classic", "double", "double-garage", "storey", "double-storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Classic-Facade-Double-Garage-2-Stry.jpg",
  },
  {
    id: "classic-single-garage",
    name: "Classic (Single Garage)",
    range: "Single Storey",
    tags: ["classic", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Classic-Facade-Narrow-Single-Garage-Single-Stry.jpg",
  },
  {
    id: "classic-plus",
    name: "Classic Plus",
    range: "Single Storey",
    tags: ["classic", "plus", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/01/CLASSIC-PLUS-SINGLE-STOREY-1.jpg",
  },
  {
    id: "classic-plus-single-garage",
    name: "Classic Plus (Wisteria Dual Occupancy)",
    range: "Duplex / Dual Occupancy",
    tags: ["classic", "plus", "duplex", "wisteria"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/07/Hudson-Homes-Dual-Living-Experts-Award-Winning-WISTERIA-24-Classic-Plus-Facade-Dual-Occupancy-Single-Stry.jpg",
  },
  {
    id: "classic-plus-double-garage",
    name: "Classic Plus (Double Storey)",
    range: "Double Storey",
    tags: ["classic", "plus", "double", "double-garage", "storey", "double-storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/01/Classic-Plus-Facade-Double-Garage-2-Stry.jpg",
  },
  {
    id: "coastal",
    name: "Coastal",
    range: "Single Storey",
    tags: ["coastal", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Coastal-Facade-Single-Storey.jpg",
  },
  {
    id: "coastal-single-garage",
    name: "Coastal (Single Garage)",
    range: "Single Storey",
    tags: ["coastal", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Coastal-Facade-Single-storey-single-garage.jpg",
  },
  {
    id: "como",
    name: "Como",
    range: "Double Storey",
    tags: ["como", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Como-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "contemporary",
    name: "Contemporary",
    range: "Double Storey",
    tags: ["contemporary", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Contemporary-Facade-2-Stry.jpg",
  },
  {
    id: "contemporary-single-garage",
    name: "Contemporary (Single Garage)",
    range: "Single Storey",
    tags: ["contemporary", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Contemporary-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "crest",
    name: "Crest",
    range: "Single Storey",
    tags: ["crest", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Crest-Facade-Single-Storey.jpg",
  },
  {
    id: "crest-single-garage",
    name: "Crest (Single Garage)",
    range: "Single Storey",
    tags: ["crest", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Crest-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "deco-double-garage",
    name: "Deco (Double Garage)",
    range: "Double Storey",
    tags: ["deco", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Deco-Facade-Double-Garage2-Stry.jpg",
  },
  {
    id: "deco-single-garage",
    name: "Deco (Single Garage)",
    range: "Double Storey",
    tags: ["deco", "double", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Deco-Facade-Single-Garage2-Stry.jpg",
  },
  {
    id: "delta",
    name: "Delta",
    range: "Double Storey",
    tags: ["delta", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Delta-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "deluxe",
    name: "Deluxe",
    range: "Double Storey",
    tags: ["deluxe", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Deluxe-Facade-2-Stry.jpg",
  },
  {
    id: "eden",
    name: "Eden",
    range: "Single Storey",
    tags: ["eden", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Eden-Facade-Single-Storey.jpg",
  },
  {
    id: "eden-single-garage",
    name: "Eden (Single Garage)",
    range: "Single Storey",
    tags: ["eden", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Eden-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "elite",
    name: "Elite",
    range: "Single Storey",
    tags: ["elite", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Elite-Facade-Single-Storey.jpg",
  },
  {
    id: "elite-single-garage",
    name: "Elite (Single Garage)",
    range: "Single Storey",
    tags: ["elite", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Elite-Facade-Single-storey-single-garage.jpg",
  },
  {
    id: "executive",
    name: "Executive",
    range: "Single Storey",
    tags: ["executive", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Executive-Facade-Single-Storey.jpg",
  },
  {
    id: "executive-single-garage",
    name: "Executive (Single Garage)",
    range: "Single Storey",
    tags: ["executive", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Executive-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "flair",
    name: "Flair",
    range: "Double Storey",
    tags: ["flair", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Flair-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "grande",
    name: "Grande",
    range: "Double Storey",
    tags: ["grande", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Grande-Facade-2-Stry.jpg",
  },
  {
    id: "hamptons-acreage",
    name: "Hamptons (Acreage / Ranch)",
    range: "Acreage / Ranch",
    tags: ["hamptons", "acreage", "ranch"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2021/02/MULBERRY-Hamptons-Facade-Single-Storey-Statesman-scaled.jpg",
  },
  {
    id: "hamptons-single",
    name: "Hamptons",
    range: "Single Storey",
    tags: ["hamptons", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/08/Hamptons-H2-Single-storey-typical-width-lot.jpg",
  },
  {
    id: "hamptons-split",
    name: "Hamptons (Split Level)",
    range: "Split Level",
    tags: ["hamptons", "split", "level"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/10/Hamptons-Facade-Split-Level-Cobalt.jpg",
  },
  {
    id: "harmony",
    name: "Harmony",
    range: "Single Storey",
    tags: ["harmony", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Harmony-Facade-Single-Storey.jpg",
  },
  {
    id: "harmony-single-garage",
    name: "Harmony (Single Garage)",
    range: "Single Storey",
    tags: ["harmony", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Harmony-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "havana",
    name: "Havana",
    range: "Single Storey",
    tags: ["havana", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Havana-Facade-Single-Storey.jpg",
  },
  {
    id: "hillsdale-single-garage",
    name: "Hillsdale (Single Garage)",
    range: "Single Storey",
    tags: ["hillsdale", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Hillsdale-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "imperial",
    name: "Imperial",
    range: "Single Storey",
    tags: ["imperial", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Imperial-Facade-Single-Storey.jpg",
  },
  {
    id: "infinity",
    name: "Infinity (Split Level)",
    range: "Split Level",
    tags: ["infinity", "split", "level"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/10/Infinity-Facade-Split-Level-Cobalt.jpg",
  },
  {
    id: "infinity-single-garage",
    name: "Infinity (Single Garage)",
    range: "Single Storey",
    tags: ["infinity", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Infinity-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "infinity-mkii",
    name: "Infinity MKii",
    range: "Single Storey",
    tags: ["infinity", "mkii", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Infinity-MKii-Facade-Single-Storey-1-scaled.jpg",
  },
  {
    id: "madison",
    name: "Madison",
    range: "Double Storey",
    tags: ["madison", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Madison-Facade-2-Stry.jpg",
  },
  {
    id: "majestic",
    name: "Majestic",
    range: "Double Storey",
    tags: ["majestic", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Majestic-Facade-Double-Garage2-Stry.jpg",
  },
  {
    id: "majestic-single-garage",
    name: "Majestic (Single Garage)",
    range: "Single Storey",
    tags: ["majestic", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Majestic-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "mantra-double-garage",
    name: "Mantra (Double Garage)",
    range: "Double Storey",
    tags: ["mantra", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mantra-Facade-Double-Garage2-Stry.jpg",
  },
  {
    id: "mantra-single-garage",
    name: "Mantra (Single Garage)",
    range: "Double Storey",
    tags: ["mantra", "double", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mantra-Facade-Single-Garage2-Stry.jpg",
  },
  {
    id: "marina",
    name: "Marina",
    range: "Double Storey",
    tags: ["marina", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Marina-Facade-2-Stry.jpg",
  },
  {
    id: "meridian",
    name: "Meridian",
    range: "Double Storey",
    tags: ["meridian", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Meridian-Facade-2-Stry.jpg",
  },
  {
    id: "merlot",
    name: "Merlot",
    range: "Single Storey",
    tags: ["merlot", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Merlot-Facade-Single-Storey.jpg",
  },
  {
    id: "metro",
    name: "Metro",
    range: "Acreage / Ranch",
    tags: ["metro", "acreage", "ranch"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MULBERRY-Metro-Facade-Single-Storey-Statesman.jpg",
  },
  {
    id: "monash",
    name: "Monash",
    range: "Double Storey",
    tags: ["monash", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Monash-Facade-2-Stry.jpg",
  },
  {
    id: "mondo",
    name: "Mondo",
    range: "Double Storey",
    tags: ["mondo", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mondo-Facade-2-Stry.jpg",
  },
  {
    id: "newport",
    name: "Newport",
    range: "Single Storey",
    tags: ["newport", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Newport-Facade-Single-Storey.jpg",
  },
  {
    id: "novare",
    name: "Novare",
    range: "Double Storey",
    tags: ["novare", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Novare-Facade-2-Stry.jpg",
  },
  {
    id: "nuvo",
    name: "Nuvo",
    range: "Single Storey",
    tags: ["nuvo", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Nuvo-Facade-Single-Storey.jpg",
  },
  {
    id: "oxford",
    name: "Oxford",
    range: "Double Storey",
    tags: ["oxford", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Oxford-Facade-2-Stry.jpg",
  },
  {
    id: "pavillion",
    name: "Pavillion",
    range: "Single Storey",
    tags: ["pavillion", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Pavillion-Facade-Single-Storey.jpg",
  },
  {
    id: "pavillion-single-garage",
    name: "Pavillion (Single Garage)",
    range: "Single Storey",
    tags: ["pavillion", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Pavillion-Facade-Single-storey-single-garage.jpg",
  },
  {
    id: "regal",
    name: "Regal",
    range: "Single Storey",
    tags: ["regal", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Regal-Facade-Single-Storey.jpg",
  },
  {
    id: "riviera",
    name: "Riviera",
    range: "Double Storey",
    tags: ["riviera", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Riviera-Facade-2-Stry-old.jpg",
  },
  {
    id: "riviera-single-garage",
    name: "Riviera (Single Garage)",
    range: "Single Storey",
    tags: ["riviera", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Riviera-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "royale",
    name: "Royale",
    range: "Double Storey",
    tags: ["royale", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Royale-Facade-2-Stry-amended.jpg",
  },
  {
    id: "saville",
    name: "Saville",
    range: "Double Storey",
    tags: ["saville", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Saville-Facade-2-Stry-amended.jpg",
  },
  {
    id: "savoy",
    name: "Savoy",
    range: "Single Storey",
    tags: ["savoy", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Savoy-Facade-Single-Storey.jpg",
  },
  {
    id: "savoy-single-garage",
    name: "Savoy (Single Garage)",
    range: "Single Storey",
    tags: ["savoy", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Savoy-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "serenity",
    name: "Serenity",
    range: "Single Storey",
    tags: ["serenity", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Serenity-Facade-Single-Storey.jpg",
  },
  {
    id: "serenity-single-garage",
    name: "Serenity (Single Garage)",
    range: "Single Storey",
    tags: ["serenity", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Serenity-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "sierra",
    name: "Sierra",
    range: "Double Storey",
    tags: ["sierra", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Sierra-Facade-2-Stry.jpg",
  },
  {
    id: "soho",
    name: "Soho",
    range: "Double Storey",
    tags: ["soho", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Soho-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "sovereign",
    name: "Sovereign",
    range: "Single Storey",
    tags: ["sovereign", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Sovereign-Facade-Single-Storey.jpg",
  },
  {
    id: "sovereign-single-garage",
    name: "Sovereign (Single Garage)",
    range: "Single Storey",
    tags: ["sovereign", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Sovereign-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "statesman",
    name: "Statesman",
    range: "Single Storey",
    tags: ["statesman", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Statesman-Facade-Single-Storey.jpg",
  },
  {
    id: "statesman-single-garage",
    name: "Statesman (Single Garage)",
    range: "Single Storey",
    tags: ["statesman", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Statesman-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "tempo",
    name: "Tempo",
    range: "Double Storey",
    tags: ["tempo", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Tempo-Facade-H2-Double-Storey.jpg",
  },
  {
    id: "urban",
    name: "Urban",
    range: "Acreage / Ranch",
    tags: ["urban", "acreage", "ranch"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MULBERRY-Urban-Facade-Single-Storey-Statesman.jpg",
  },
  {
    id: "vibe",
    name: "Vibe",
    range: "Single Storey",
    tags: ["vibe", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Vibe-Facade-Single-Storey.jpg",
  },
  {
    id: "vienna",
    name: "Vienna",
    range: "Single Storey",
    tags: ["vienna", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Vienna-Facade-Single-Storey.jpg",
  },
  {
    id: "visage",
    name: "Visage",
    range: "Single Storey",
    tags: ["visage", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Visage-Facade-Single-Storey.jpg",
  },
  {
    id: "vista",
    name: "Vista",
    range: "Double Storey",
    tags: ["vista", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/TURQUOISE-Vista-Facade-2-Stry.jpg",
  },
  {
    id: "vogue",
    name: "Vogue",
    range: "Single Storey",
    tags: ["vogue", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Vogue-Facade-Single-Storey.jpg",
  },
  {
    id: "windsor",
    name: "Windsor",
    range: "Double Storey",
    tags: ["windsor", "double", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Windsor-Facade-2-Stry.jpg",
  },
];