/* Auto-generated from the hudsonhomes.com.au facade galleries. */
import type { FacadeItem } from "./facadeLibrary";

export const HUDSON_FACADES: FacadeItem[] = [
  {
    id: "allure",
    name: "Allure",
    range: "Double Storey",
    tags: ["allure", "double", "double-garage", "storey"],
    url: "/facades/allure.png",
  },
  {
    id: "ascot",
    name: "Ascot",
    range: "Double Storey",
    tags: ["ascot", "double", "double-garage", "storey"],
    url: "/facades/ascot.png",
  },
  {
    id: "ashton",
    name: "Ashton",
    range: "Double Storey",
    tags: ["ashton", "double", "double-garage", "storey"],
    url: "/facades/ashton.png",
  },
  {
    id: "aspen",
    name: "Aspen",
    range: "Single Storey",
    tags: ["aspen", "single", "double-garage", "storey"],
    url: "/facades/aspen.png",
  },
  {
    id: "aspen-single-garage",
    name: "Aspen (Single Garage)",
    range: "Single Storey",
    tags: ["aspen", "single", "single-garage", "storey"],
    url: "/facades/aspen-single-garage_widescreen.jpg",
  },
  {
    id: "avalon",
    name: "Avalon",
    range: "Single Storey",
    tags: ["avalon", "single", "double-garage", "storey"],
    url: "/facades/avalon_widescreen.jpg",
  },
  {
    id: "avoca",
    name: "Avoca",
    range: "Single Storey",
    tags: ["avoca", "single", "double-garage", "storey"],
    url: "/facades/avoca_widescreen.jpg",
  },
  {
    id: "avoca-single-garage",
    name: "Avoca (Single Garage)",
    range: "Single Storey",
    tags: ["avoca", "single", "single-garage", "storey"],
    url: "/facades/avoca-single-garage_widescreen.jpg",
  },
  {
    id: "banksia",
    name: "Banksia",
    range: "Single Storey",
    tags: ["banksia", "single", "double-garage", "storey"],
    url: "/facades/banksia_widescreen.jpg",
  },
  {
    id: "banksia-single-garage",
    name: "Banksia (Single Garage)",
    range: "Single Storey",
    tags: ["banksia", "single", "single-garage", "storey"],
    url: "/facades/banksia-single-garage_widescreen.jpg",
  },
  {
    id: "bayside",
    name: "Bayside",
    range: "Single Storey",
    tags: ["bayside", "single", "double-garage", "storey"],
    url: "/facades/bayside_widescreen.jpg",
  },
  {
    id: "bayside-single-garage",
    name: "Bayside (Single Garage)",
    range: "Single Storey",
    tags: ["bayside", "single", "single-garage", "storey"],
    url: "/facades/bayside-single-garage_widescreen.jpg",
  },
  {
    id: "breeze",
    name: "Breeze",
    range: "Single Storey",
    tags: ["breeze", "single", "double-garage", "storey"],
    url: "/facades/breeze.png",
  },
  {
    id: "breeze-single-garage",
    name: "Breeze (Single Garage)",
    range: "Single Storey",
    tags: ["breeze", "single", "single-garage", "storey"],
    url: "/facades/breeze-single-garage_widescreen.jpg",
  },
  {
    id: "cambridge",
    name: "Cambridge",
    range: "Double Storey",
    tags: ["cambridge", "double", "double-garage", "storey"],
    url: "/facades/cambridge.png",
  },
  {
    id: "centro",
    name: "Centro",
    range: "Double Storey",
    tags: ["centro", "double", "double-garage", "storey"],
    url: "/facades/centro.png",
  },
  {
    id: "chateaux",
    name: "Chateaux",
    range: "Single Storey",
    tags: ["chateaux", "single", "double-garage", "storey"],
    url: "/facades/chateaux.png",
  },
  {
    id: "chateaux-single-garage",
    name: "Chateaux (Single Garage)",
    range: "Single Storey",
    tags: ["chateaux", "single", "single-garage", "storey"],
    url: "/facades/chateaux-single-garage.png",
  },
  {
    id: "classic",
    name: "Classic",
    range: "Single Storey",
    tags: ["classic", "single", "double-garage", "storey"],
    url: "/facades/classic.png",
  },
  {
    id: "classic-double-garage",
    name: "Classic (Double Storey)",
    range: "Double Storey",
    tags: ["classic", "double", "double-garage", "storey", "double-storey"],
    url: "/facades/classic-double-garage.png",
  },
  {
    id: "classic-single-garage",
    name: "Classic (Single Garage)",
    range: "Single Storey",
    tags: ["classic", "single", "single-garage", "storey"],
    url: "/facades/classic-single-garage.png",
  },
  {
    id: "classic-plus",
    name: "Classic Plus",
    range: "Single Storey",
    tags: ["classic", "plus", "single", "double-garage", "storey"],
    url: "/facades/classic-plus.png",
  },
  {
    id: "classic-plus-single-garage",
    name: "Classic Plus (Wisteria Dual Occupancy)",
    range: "Duplex / Dual Occupancy",
    tags: ["classic", "plus", "duplex", "wisteria"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2024/07/Hudson-Homes-Dual-Living-Experts-Award-Winning-WISTERIA-24-Classic-Plus-Facade-Dual-Occupancy-Single-Stry.jpg",
  },
  {
    id: "classic-plus-double-garage",
    name: "Classic Plus (Double Storey)",
    range: "Double Storey",
    tags: ["classic", "plus", "double", "double-garage", "storey", "double-storey"],
    url: "/facades/classic-plus-double-garage.png",
  },
  {
    id: "coastal",
    name: "Coastal",
    range: "Single Storey",
    tags: ["coastal", "single", "double-garage", "storey"],
    url: "/facades/coastal_widescreen.jpg",
  },
  {
    id: "coastal-single-garage",
    name: "Coastal (Single Garage)",
    range: "Single Storey",
    tags: ["coastal", "single", "single-garage", "storey"],
    url: "/facades/coastal-single-garage_widescreen.jpg",
  },
  {
    id: "como",
    name: "Como",
    range: "Double Storey",
    tags: ["como", "double", "double-garage", "storey"],
    url: "/facades/como.png",
  },
  {
    id: "contemporary",
    name: "Contemporary",
    range: "Double Storey",
    tags: ["contemporary", "double", "double-garage", "storey"],
    url: "/facades/contemporary.png",
  },
  {
    id: "contemporary-single-garage",
    name: "Contemporary (Single Garage)",
    range: "Single Storey",
    tags: ["contemporary", "single", "single-garage", "storey"],
    url: "/facades/contemporary-single-garage.png",
  },
  {
    id: "crest",
    name: "Crest",
    range: "Single Storey",
    tags: ["crest", "single", "double-garage", "storey"],
    url: "/facades/crest_widescreen.jpg",
  },
  {
    id: "crest-single-garage",
    name: "Crest (Single Garage)",
    range: "Single Storey",
    tags: ["crest", "single", "single-garage", "storey"],
    url: "/facades/crest-single-garage_widescreen.jpg",
  },
  {
    id: "deco-double-garage",
    name: "Deco (Double Garage)",
    range: "Double Storey",
    tags: ["deco", "double", "double-garage", "storey"],
    url: "/facades/deco-double-garage.png",
  },
  {
    id: "deco-single-garage",
    name: "Deco (Single Garage)",
    range: "Double Storey",
    tags: ["deco", "double", "single-garage", "storey"],
    url: "/facades/deco-single-garage.png",
  },
  {
    id: "delta",
    name: "Delta",
    range: "Double Storey",
    tags: ["delta", "double", "double-garage", "storey"],
    url: "/facades/delta.png",
  },
  {
    id: "deluxe",
    name: "Deluxe",
    range: "Double Storey",
    tags: ["deluxe", "double", "double-garage", "storey"],
    url: "/facades/deluxe.png",
  },
  {
    id: "eden",
    name: "Eden",
    range: "Single Storey",
    tags: ["eden", "single", "double-garage", "storey"],
    url: "/facades/eden_widescreen.jpg",
  },
  {
    id: "eden-single-garage",
    name: "Eden (Single Garage)",
    range: "Single Storey",
    tags: ["eden", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Eden-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "elite",
    name: "Elite",
    range: "Single Storey",
    tags: ["elite", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Elite-Facade-Single-Storey.jpg",
  },
  {
    id: "elite-single-garage",
    name: "Elite (Single Garage)",
    range: "Single Storey",
    tags: ["elite", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Elite-Facade-Single-storey-single-garage.jpg",
  },
  {
    id: "executive",
    name: "Executive",
    range: "Single Storey",
    tags: ["executive", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Executive-Facade-Single-Storey.jpg",
  },
  {
    id: "executive-single-garage",
    name: "Executive (Single Garage)",
    range: "Single Storey",
    tags: ["executive", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Executive-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "flair",
    name: "Flair",
    range: "Double Storey",
    tags: ["flair", "double", "double-garage", "storey"],
    url: "/facades/flair.png",
  },
  {
    id: "grande",
    name: "Grande",
    range: "Double Storey",
    tags: ["grande", "double", "double-garage", "storey"],
    url: "/facades/grande.png",
  },
  {
    id: "hamptons-acreage",
    name: "Hamptons (Acreage / Ranch)",
    range: "Acreage / Ranch",
    tags: ["hamptons", "acreage", "ranch"],
    url: "/facades/hamptons-acreage.png",
  },
  {
    id: "hamptons-single",
    name: "Hamptons",
    range: "Single Storey",
    tags: ["hamptons", "single", "double-garage", "storey"],
    url: "/facades/hamptons-single.png",
  },
  {
    id: "hamptons-split",
    name: "Hamptons (Split Level)",
    range: "Split Level",
    tags: ["hamptons", "split", "level"],
    url: "/facades/hamptons-split.png",
  },
  {
    id: "harmony",
    name: "Harmony",
    range: "Single Storey",
    tags: ["harmony", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Harmony-Facade-Single-Storey.jpg",
  },
  {
    id: "harmony-single-garage",
    name: "Harmony (Single Garage)",
    range: "Single Storey",
    tags: ["harmony", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Harmony-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "havana",
    name: "Havana",
    range: "Single Storey",
    tags: ["havana", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Havana-Facade-Single-Storey.jpg",
  },
  {
    id: "hillsdale-single-garage",
    name: "Hillsdale (Single Garage)",
    range: "Single Storey",
    tags: ["hillsdale", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Hillsdale-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "imperial",
    name: "Imperial",
    range: "Single Storey",
    tags: ["imperial", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Imperial-Facade-Single-Storey.jpg",
  },
  {
    id: "infinity",
    name: "Infinity (Split Level)",
    range: "Split Level",
    tags: ["infinity", "split", "level"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/10/Infinity-Facade-Split-Level-Cobalt.jpg",
  },
  {
    id: "infinity-single-garage",
    name: "Infinity (Single Garage)",
    range: "Single Storey",
    tags: ["infinity", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Infinity-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "infinity-mkii",
    name: "Infinity MKii",
    range: "Single Storey",
    tags: ["infinity", "mkii", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Infinity-MKii-Facade-Single-Storey-1-scaled.jpg",
  },
  {
    id: "madison",
    name: "Madison",
    range: "Double Storey",
    tags: ["madison", "double", "double-garage", "storey"],
    url: "/facades/madison.png",
  },
  {
    id: "majestic",
    name: "Majestic",
    range: "Double Storey",
    tags: ["majestic", "double", "double-garage", "storey"],
    url: "/facades/majestic.png",
  },
  {
    id: "majestic-single-garage",
    name: "Majestic (Single Garage)",
    range: "Single Storey",
    tags: ["majestic", "single", "single-garage", "storey"],
    url: "/facades/majestic-single-garage.png",
  },
  {
    id: "mantra-double-garage",
    name: "Mantra (Double Garage)",
    range: "Double Storey",
    tags: ["mantra", "double", "double-garage", "storey"],
    url: "/facades/mantra-double-garage.png",
  },
  {
    id: "mantra-single-garage",
    name: "Mantra (Single Garage)",
    range: "Double Storey",
    tags: ["mantra", "double", "single-garage", "storey"],
    url: "/facades/mantra-single-garage_widescreen.jpg",
  },
  {
    id: "marina",
    name: "Marina",
    range: "Double Storey",
    tags: ["marina", "double", "double-garage", "storey"],
    url: "/facades/marina.png",
  },
  {
    id: "meridian",
    name: "Meridian",
    range: "Double Storey",
    tags: ["meridian", "double", "double-garage", "storey"],
    url: "/facades/meridian.png",
  },
  {
    id: "merlot",
    name: "Merlot",
    range: "Single Storey",
    tags: ["merlot", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Merlot-Facade-Single-Storey.jpg",
  },
  {
    id: "metro",
    name: "Metro",
    range: "Acreage / Ranch",
    tags: ["metro", "acreage", "ranch"],
    url: "/facades/metro.png",
  },
  {
    id: "monash",
    name: "Monash",
    range: "Double Storey",
    tags: ["monash", "double", "double-garage", "storey"],
    url: "/facades/monash.png",
  },
  {
    id: "mondo",
    name: "Mondo",
    range: "Double Storey",
    tags: ["mondo", "double", "double-garage", "storey"],
    url: "/facades/mondo.png",
  },
  {
    id: "newport",
    name: "Newport",
    range: "Single Storey",
    tags: ["newport", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Newport-Facade-Single-Storey.jpg",
  },
  {
    id: "novare",
    name: "Novare",
    range: "Double Storey",
    tags: ["novare", "double", "double-garage", "storey"],
    url: "/facades/novare.png",
  },
  {
    id: "nuvo",
    name: "Nuvo",
    range: "Single Storey",
    tags: ["nuvo", "single", "double-garage", "storey"],
    url: "/facades/nuvo.png",
  },
  {
    id: "oxford",
    name: "Oxford",
    range: "Double Storey",
    tags: ["oxford", "double", "double-garage", "storey"],
    url: "/facades/oxford.png",
  },
  {
    id: "pavillion",
    name: "Pavillion",
    range: "Single Storey",
    tags: ["pavillion", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Pavillion-Facade-Single-Storey.jpg",
  },
  {
    id: "pavillion-single-garage",
    name: "Pavillion (Single Garage)",
    range: "Single Storey",
    tags: ["pavillion", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Pavillion-Facade-Single-storey-single-garage.jpg",
  },
  {
    id: "regal",
    name: "Regal",
    range: "Single Storey",
    tags: ["regal", "single", "double-garage", "storey"],
    url: "/facades/regal.png",
  },
  {
    id: "riviera",
    name: "Riviera",
    range: "Double Storey",
    tags: ["riviera", "double", "double-garage", "storey"],
    url: "/facades/riviera.png",
  },
  {
    id: "riviera-single-garage",
    name: "Riviera (Single Garage)",
    range: "Single Storey",
    tags: ["riviera", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Riviera-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "royale",
    name: "Royale",
    range: "Double Storey",
    tags: ["royale", "double", "double-garage", "storey"],
    url: "/facades/royale.png",
  },
  {
    id: "saville",
    name: "Saville",
    range: "Double Storey",
    tags: ["saville", "double", "double-garage", "storey"],
    url: "/facades/saville.png",
  },
  {
    id: "savoy",
    name: "Savoy",
    range: "Single Storey",
    tags: ["savoy", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Savoy-Facade-Single-Storey.jpg",
  },
  {
    id: "savoy-single-garage",
    name: "Savoy (Single Garage)",
    range: "Single Storey",
    tags: ["savoy", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Savoy-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "serenity",
    name: "Serenity",
    range: "Single Storey",
    tags: ["serenity", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Serenity-Facade-Single-Storey.jpg",
  },
  {
    id: "serenity-single-garage",
    name: "Serenity (Single Garage)",
    range: "Single Storey",
    tags: ["serenity", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Serenity-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "sierra",
    name: "Sierra",
    range: "Double Storey",
    tags: ["sierra", "double", "double-garage", "storey"],
    url: "/facades/sierra.png",
  },
  {
    id: "soho",
    name: "Soho",
    range: "Double Storey",
    tags: ["soho", "double", "double-garage", "storey"],
    url: "/facades/soho.png",
  },
  {
    id: "sovereign",
    name: "Sovereign",
    range: "Single Storey",
    tags: ["sovereign", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Sovereign-Facade-Single-Storey.jpg",
  },
  {
    id: "sovereign-single-garage",
    name: "Sovereign (Single Garage)",
    range: "Single Storey",
    tags: ["sovereign", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Sovereign-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "statesman",
    name: "Statesman",
    range: "Single Storey",
    tags: ["statesman", "single", "double-garage", "storey"],
    url: "/facades/statesman.png",
  },
  {
    id: "statesman-single-garage",
    name: "Statesman (Single Garage)",
    range: "Single Storey",
    tags: ["statesman", "single", "single-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/01/Statesman-Facade-Single-Storey-single-garage.jpg",
  },
  {
    id: "tempo",
    name: "Tempo",
    range: "Double Storey",
    tags: ["tempo", "double", "double-garage", "storey"],
    url: "/facades/tempo.png",
  },
  {
    id: "urban",
    name: "Urban",
    range: "Acreage / Ranch",
    tags: ["urban", "acreage", "ranch"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/MULBERRY-Urban-Facade-Single-Storey-Statesman.jpg",
  },
  {
    id: "vibe",
    name: "Vibe",
    range: "Single Storey",
    tags: ["vibe", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Vibe-Facade-Single-Storey.jpg",
  },
  {
    id: "vienna",
    name: "Vienna",
    range: "Single Storey",
    tags: ["vienna", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Vienna-Facade-Single-Storey.jpg",
  },
  {
    id: "visage",
    name: "Visage",
    range: "Single Storey",
    tags: ["visage", "single", "double-garage", "storey"],
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Visage-Facade-Single-Storey.jpg",
  },
  {
    id: "vista",
    name: "Vista",
    range: "Double Storey",
    tags: ["vista", "double", "double-garage", "storey"],
    url: "/facades/vista.png",
  },
  {
    id: "vogue",
    name: "Vogue",
    range: "Single Storey",
    tags: ["vogue", "single", "double-garage", "storey"],
    url: "/facades/vogue.png",
  },
  {
    id: "windsor",
    name: "Windsor",
    range: "Double Storey",
    tags: ["windsor", "double", "double-garage", "storey"],
    url: "/facades/windsor.png",
  },
];