/* Auto-generated from hudsonhomes.com.au home-design pages.
 * Every floorplan drawing is the publisher's own 2000px PNG — no cropping or
 * clean-up needed, so all plans render at identical print quality. */

export interface FloorplanRecord {
  design: string;
  label: string;
  beds: string;
  baths: string;
  cars: string;
  /** Total area in m² */
  size: string;
  /** Minimum lot width in m */
  frontage: string;
  url: string;
}

export const HUDSON_FLOORPLANS: FloorplanRecord[] = [
  {
    design: "Amaranth",
    label: "Amaranth 23A",
    beds: "3",
    baths: "3",
    cars: "2",
    size: "210.01",
    frontage: "12.02",
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2026/07/Amaranth-23A.png",
  },
  {
    design: "Amaranth",
    label: "Amaranth 23B",
    beds: "4",
    baths: "4",
    cars: "2",
    size: "210.01",
    frontage: "12.02",
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2026/07/Amaranth-23B.png",
  },
  {
    design: "Alabaster",
    label: "Alabaster 31",
    beds: "6",
    baths: "4",
    cars: "2",
    size: "284.86",
    frontage: "17.80",
    url: "/floorplans/ALABASTER 31_ CLASSIC_BROCHURE_19.09.2025.png",
  },
  {
    design: "Alabaster",
    label: "Alabaster 36",
    beds: "8",
    baths: "4",
    cars: "2",
    size: "330.66",
    frontage: "18.00",
    url: "/floorplans/ALABASTER 36_ CLASSIC_BROCHURE_19.09.2025.png",
  },
  {
    design: "Alabaster",
    label: "Alabaster 40",
    beds: "8",
    baths: "4",
    cars: "2",
    size: "373.02",
    frontage: "18.00",
    url: "/floorplans/ALABASTER 40_ CLASSIC_BROCHURE_19.09.2025.png",
  },
  {
    design: "Charcoal",
    label: "Charcoal 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "222.56",
    frontage: "12.49",
    url: "/floorplans/CHARCOAL 24.png",
  },
  {
    design: "Maroon",
    label: "Maroon 26",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "244.42",
    frontage: "12.50",
    url: "/floorplans/MAROON 26 (QLD) 20.03.25.png",
  },
  {
    design: "Maroon",
    label: "Maroon 28",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "261.34",
    frontage: "14.14",
    url: "/floorplans/MAROON 28 (QLD) LH BROCHURE 06.05.25.png",
  },
  {
    design: "Raven",
    label: "Raven 45",
    beds: "10",
    baths: "6",
    cars: "2",
    size: "418.52",
    frontage: "15.00",
    url: "/floorplans/RAVEN 45_CLASSIC_BROCHURE_27.05.25.png",
  },
  {
    design: "Raven",
    label: "Raven 55",
    beds: "10",
    baths: "6",
    cars: "2",
    size: "508.16",
    frontage: "17.43",
    url: "/floorplans/RAVEN 55.png",
  },
  {
    design: "Cayenne",
    label: "Cayenne 42",
    beds: "6",
    baths: "5",
    cars: "2",
    size: "389.36",
    frontage: "15.00",
    url: "/floorplans/CAYENNE 42_CLASSIC_BROCHURE_02.05.25.png",
  },
  {
    design: "Cayenne",
    label: "Cayenne 45",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "420.28",
    frontage: "17.35",
    url: "/floorplans/CAYENNE 45.png",
  },
  {
    design: "Cayenne",
    label: "Cayenne 47",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "436.94",
    frontage: "15",
    url: "/floorplans/CAYENNE 47_CLASSIC_BROCHURE_02.05.25.png",
  },
  {
    design: "Cayenne",
    label: "Cayenne 56",
    beds: "10",
    baths: "5",
    cars: "2",
    size: "523.26",
    frontage: "17.35",
    url: "/floorplans/CAYENNE 56.png",
  },
  {
    design: "Teal",
    label: "Teal 29",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "265.59",
    frontage: "16.83",
    url: "/floorplans/TEAL 29_ CLASSIC_BROCHURE_08.12.2025.png",
  },
  {
    design: "Teal",
    label: "Teal 33",
    beds: "7",
    baths: "4",
    cars: "2",
    size: "306.25",
    frontage: "17.92",
    url: "/floorplans/TEAL 33_ CLASSIC_BROCHURE_05.06.2026.png",
  },
  {
    design: "Teal",
    label: "Teal 45",
    beds: "6",
    baths: "6",
    cars: "3",
    size: "423.10",
    frontage: "17.43",
    url: "/floorplans/TEAL 45.png",
  },
  {
    design: "Teal",
    label: "Teal 48",
    beds: "7",
    baths: "5.5",
    cars: "3",
    size: "443.45",
    frontage: "17.43",
    url: "/floorplans/TEAL 48.png",
  },
  {
    design: "Sabel (QLD ONLY)",
    label: "Sabel (QLD ONLY) 28",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "257.29",
    frontage: "",
    url: "/floorplans/SABEL 28 (QLD) CLASSIC LH BROCHURE 17.01.25.png",
  },
  {
    design: "Hazel",
    label: "Hazel 14",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "125.80",
    frontage: "9.95",
    url: "/floorplans/HAZEL 14.png",
  },
  {
    design: "Hazel",
    label: "Hazel 15",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "142.05",
    frontage: "9.95",
    url: "/floorplans/HAZEL 15.png",
  },
  {
    design: "Hazel",
    label: "Hazel 17",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "158.08",
    frontage: "9.95",
    url: "/floorplans/HAZEL 17.png",
  },
  {
    design: "Hazel",
    label: "Hazel 19",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "173.20",
    frontage: "9.95",
    url: "/floorplans/HAZEL 19.png",
  },
  {
    design: "Olive",
    label: "Olive 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "210.86",
    frontage: "12.87",
    url: "/floorplans/OLIVE 23.png",
  },
  {
    design: "Blanc",
    label: "Blanc 27",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "246.93",
    frontage: "14.91",
    url: "/floorplans/BLANC 27.png",
  },
  {
    design: "Amber",
    label: "Amber 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "192.24",
    frontage: "12.39",
    url: "/floorplans/AMBER 21.png",
  },
  {
    design: "Amber",
    label: "Amber 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "210.63",
    frontage: "12.39",
    url: "/floorplans/AMBER 23.png",
  },
  {
    design: "Amber",
    label: "Amber 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "241.57",
    frontage: "13.47",
    url: "/floorplans/AMBER 26.png",
  },
  {
    design: "Amber",
    label: "Amber 30",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "282.99",
    frontage: "13.47",
    url: "/floorplans/AMBER 30.png",
  },
  {
    design: "Azure",
    label: "Azure 19",
    beds: "3",
    baths: "2",
    cars: "2",
    size: "177.08",
    frontage: "12.39",
    url: "/floorplans/AZURE 19.png",
  },
  {
    design: "Azure",
    label: "Azure 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "197.08",
    frontage: "12.87",
    url: "/floorplans/AZURE 21.png",
  },
  {
    design: "Azure",
    label: "Azure 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "208.71",
    frontage: "12.39",
    url: "/floorplans/AZURE 23.png",
  },
  {
    design: "Azure",
    label: "Azure 25",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "235.44",
    frontage: "12.50",
    url: "/floorplans/AZURE 25.png",
  },
  {
    design: "Burgundy",
    label: "Burgundy 27",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "252.01",
    frontage: "13.33",
    url: "/floorplans/BURGUNDY 27_CLASSIC_RH_01.06.2020.png",
  },
  {
    design: "Burgundy",
    label: "Burgundy 30",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "277.51",
    frontage: "13.57",
    url: "/floorplans/BURGUNDY 30_CLASSIC_RH_01.06.2020.png",
  },
  {
    design: "Burgundy",
    label: "Burgundy 32",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "298.12",
    frontage: "13.57",
    url: "/floorplans/BURGUNDY 32_CLASSIC_RH_01.06.2020.png",
  },
  {
    design: "Burgundy",
    label: "Burgundy 34",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "317.03",
    frontage: "13.57",
    url: "/floorplans/BURGUNDY 34_CLASSIC_RH_01.06.2020.png",
  },
  {
    design: "Canary",
    label: "Canary 1",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "117.64",
    frontage: "12.99",
    url: "/floorplans/CANARY 1.png",
  },
  {
    design: "Canary",
    label: "Canary 2",
    beds: "3",
    baths: "1",
    cars: "1",
    size: "113.03",
    frontage: "13.95",
    url: "/floorplans/CANARY 2.png",
  },
  {
    design: "Canary",
    label: "Canary 3",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "127.20",
    frontage: "15.18",
    url: "/floorplans/CANARY 3.png",
  },
  {
    design: "Canary",
    label: "Canary 4",
    beds: "3",
    baths: "1",
    cars: "1",
    size: "117.36",
    frontage: "14.43",
    url: "/floorplans/CANARY 4.png",
  },
  {
    design: "Carolina",
    label: "Carolina 22",
    beds: "3",
    baths: "2",
    cars: "2",
    size: "202.58",
    frontage: "9.95",
    url: "/floorplans/CAROLINA 22_CLASSIC_RH_02.03.2023.png",
  },
  {
    design: "Carolina",
    label: "Carolina 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "222.48",
    frontage: "9.95",
    url: "/floorplans/CAROLINA 24_CLASSIC_RH_02.03.2023.png",
  },
  {
    design: "Carolina",
    label: "Carolina 26",
    beds: "5",
    baths: "2",
    cars: "2",
    size: "242.63",
    frontage: "9.95",
    url: "/floorplans/CAROLINA 26_CLASSIC_RH_15.05.2023.png",
  },
  {
    design: "Carolina",
    label: "Carolina 29",
    beds: "6",
    baths: "3",
    cars: "2",
    size: "266.70",
    frontage: "9.95",
    url: "/floorplans/CAROLINA 29_CLASSIC_RH_15.05.2023.png",
  },
  {
    design: "Carmine",
    label: "Carmine 17",
    beds: "3",
    baths: "2",
    cars: "2",
    size: "162.11",
    frontage: "11.79",
    url: "/floorplans/CARMINE 17.png",
  },
  {
    design: "Carmine",
    label: "Carmine 19",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "180.02",
    frontage: "11.79",
    url: "/floorplans/CARMINE 19.png",
  },
  {
    design: "Carmine",
    label: "Carmine 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "193.57",
    frontage: "11.79",
    url: "/floorplans/CARMINE 21.png",
  },
  {
    design: "Carmine",
    label: "Carmine 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "215.19",
    frontage: "11.79",
    url: "/floorplans/CARMINE 23.png",
  },
  {
    design: "Cedar",
    label: "Cedar 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "242.35",
    frontage: "17.07",
    url: "/floorplans/CEDAR 26.png",
  },
  {
    design: "Cedar",
    label: "Cedar 28",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "261.44",
    frontage: "17.07",
    url: "/floorplans/CEDAR 28.png",
  },
  {
    design: "Cedar",
    label: "Cedar 31",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "291.51",
    frontage: "18.03",
    url: "/floorplans/CEDAR 31.png",
  },
  {
    design: "Cedar",
    label: "Cedar 34",
    beds: "5",
    baths: "2",
    cars: "2",
    size: "318.36",
    frontage: "18.63",
    url: "/floorplans/CEDAR 34.png",
  },
  {
    design: "Cerise",
    label: "Cerise 20",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "181.35",
    frontage: "9.01",
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/10/Cerise20_standard.jpg",
  },
  {
    design: "Cinnamon",
    label: "Cinnamon 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "218.03",
    frontage: "13.33",
    url: "/floorplans/CINNAMON 23.png",
  },
  {
    design: "Cinnamon",
    label: "Cinnamon 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "237.61",
    frontage: "13.57",
    url: "/floorplans/CINNAMON 26.png",
  },
  {
    design: "Cinnamon",
    label: "Cinnamon 30",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "275.83",
    frontage: "14.41",
    url: "/floorplans/CINNAMON 30.png",
  },
  {
    design: "Cinnamon",
    label: "Cinnamon 36",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "338.87",
    frontage: "15.13",
    url: "/floorplans/CINNAMON 36.png",
  },
  {
    design: "Cobalt",
    label: "Cobalt 22",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "202.63",
    frontage: "12.97",
    url: "/floorplans/COBALT 22.png",
  },
  {
    design: "Cobalt",
    label: "Cobalt 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "242.03",
    frontage: "13.45",
    url: "/floorplans/COBALT 26.png",
  },
  {
    design: "Cobalt",
    label: "Cobalt 30",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "278.98",
    frontage: "13.45",
    url: "/floorplans/COBALT 30.png",
  },
  {
    design: "Cobalt",
    label: "Cobalt 36",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "332.60",
    frontage: "14.41",
    url: "/floorplans/COBALT 36.png",
  },
  {
    design: "Coral",
    label: "Coral 19",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "181.12",
    frontage: "10.21",
    url: "/floorplans/CORAL 19.png",
  },
  {
    design: "Coral",
    label: "Coral 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "198.08",
    frontage: "11.30",
    url: "/floorplans/CORAL 21.png",
  },
  {
    design: "Coral",
    label: "Coral 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "217.68",
    frontage: "12.47",
    url: "/floorplans/CORAL 23.png",
  },
  {
    design: "Coral",
    label: "Coral 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "240.93",
    frontage: "13.03",
    url: "/floorplans/CORAL 26.png",
  },
  {
    design: "Crimson",
    label: "Crimson 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "224.56",
    frontage: "13.83",
    url: "/floorplans/CRIMSON 24.png",
  },
  {
    design: "Crimson",
    label: "Crimson 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "245.04",
    frontage: "14.67",
    url: "/floorplans/CRIMSON 26.png",
  },
  {
    design: "Crimson",
    label: "Crimson 29",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "273.85",
    frontage: "17.43",
    url: "/floorplans/CRIMSON 29.png",
  },
  {
    design: "Crimson",
    label: "Crimson 33",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "302.45",
    frontage: "17.43",
    url: "/floorplans/CRIMSON 33.png",
  },
  {
    design: "Ebony (QLD Only)",
    label: "Ebony (QLD Only) 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "225.26",
    frontage: "13.11",
    url: "/floorplans/EBONY 24.png",
  },
  {
    design: "Ebony (QLD Only)",
    label: "Ebony (QLD Only) 27",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "249.27",
    frontage: "13.83",
    url: "/floorplans/EBONY 27.png",
  },
  {
    design: "Ebony (QLD Only)",
    label: "Ebony (QLD Only) 29",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "269.24",
    frontage: "17.07",
    url: "/floorplans/EBONY 29_CLASSIC_BROCHURE_RH_17.01.18.png",
  },
  {
    design: "Ebony (QLD Only)",
    label: "Ebony (QLD Only) 32",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "293.23",
    frontage: "18.15",
    url: "/floorplans/EBONY 32.png",
  },
  {
    design: "Emerald",
    label: "Emerald 28",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "261.45",
    frontage: "10.81",
    url: "/floorplans/EMERALD 28.png",
  },
  {
    design: "Emerald",
    label: "Emerald 39",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "363.29",
    frontage: "14.99",
    url: "/floorplans/EMERALD 39.png",
  },
  {
    design: "Emerald",
    label: "Emerald 42",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "392.45",
    frontage: "15.23",
    url: "/floorplans/EMERALD 42.png",
  },
  {
    design: "Emerald",
    label: "Emerald 44",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "408.67",
    frontage: "15.23",
    url: "/floorplans/EMERALD 44.png",
  },
  {
    design: "Emerald",
    label: "Emerald 47",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "438.52",
    frontage: "15.23",
    url: "/floorplans/EMERALD 47.png",
  },
  {
    design: "Indigo (QLD Only)",
    label: "Indigo (QLD Only) 15",
    beds: "3",
    baths: "1",
    cars: "1",
    size: "144.97",
    frontage: "10.47",
    url: "/floorplans/INDIGO 15.png",
  },
  {
    design: "Indigo (QLD Only)",
    label: "Indigo (QLD Only) 17",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "162.18",
    frontage: "10.47",
    url: "/floorplans/INDIGO 17.png",
  },
  {
    design: "Indigo (QLD Only)",
    label: "Indigo (QLD Only) 19",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "174.92",
    frontage: "10.47",
    url: "/floorplans/INDIGO 19.png",
  },
  {
    design: "Indigo (QLD Only)",
    label: "Indigo (QLD Only) 22",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "206.17",
    frontage: "11.31",
    url: "/floorplans/INDIGO 22.png",
  },
  {
    design: "Iris",
    label: "Iris 15",
    beds: "3",
    baths: "1",
    cars: "1",
    size: "139.07",
    frontage: "9.25",
    url: "/floorplans/IRIS 15.png",
  },
  {
    design: "Iris",
    label: "Iris 17",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "159.99",
    frontage: "9.25",
    url: "/floorplans/IRIS 17.png",
  },
  {
    design: "Iris",
    label: "Iris 18",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "168.58",
    frontage: "9.25",
    url: "/floorplans/IRIS 18.png",
  },
  {
    design: "Iris",
    label: "Iris 21",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "195.59",
    frontage: "10.95",
    url: "/floorplans/IRIS 21.png",
  },
  {
    design: "Ivory",
    label: "Ivory 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "199.23",
    frontage: "12.73",
    url: "/floorplans/IVORY 21.png",
  },
  {
    design: "Ivory",
    label: "Ivory 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "211.51",
    frontage: "13.23",
    url: "/floorplans/IVORY 23.png",
  },
  {
    design: "Ivory",
    label: "Ivory 25",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "232.90",
    frontage: "13.71",
    url: "/floorplans/IVORY 25.png",
  },
  {
    design: "Ivory",
    label: "Ivory 27",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "254.56",
    frontage: "14.43",
    url: "/floorplans/IVORY 27.png",
  },
  {
    design: "Ivory",
    label: "Ivory 29",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "273.92",
    frontage: "14.67",
    url: "/floorplans/IVORY 29.png",
  },
  {
    design: "Jade (QLD Only)",
    label: "Jade (QLD Only) 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "196.98",
    frontage: "12.87",
    url: "/floorplans/JADE 21.png",
  },
  {
    design: "Jade (QLD Only)",
    label: "Jade (QLD Only) 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "216.11",
    frontage: "13.11",
    url: "/floorplans/JADE 23.png",
  },
  {
    design: "Jasper",
    label: "Jasper 17",
    beds: "3",
    baths: "2",
    cars: "2",
    size: "161.71",
    frontage: "11.41",
    url: "/floorplans/JASPER 17.png",
  },
  {
    design: "Jasper",
    label: "Jasper 20",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "185.15",
    frontage: "11.77",
    url: "/floorplans/JASPER 20.png",
  },
  {
    design: "Jasper",
    label: "Jasper 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "219.83",
    frontage: "11.89",
    url: "/floorplans/JASPER 24.png",
  },
  {
    design: "Jasper",
    label: "Jasper 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "241.82",
    frontage: "12.49",
    url: "/floorplans/JASPER 26.png",
  },
  {
    design: "Lime",
    label: "Lime 19",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "176.46",
    frontage: "8.99",
    url: "/floorplans/LIME 19_CLASSIC_RH_02.05.2023.png",
  },
  {
    design: "Lime",
    label: "Lime 21",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "195.08",
    frontage: "8.99",
    url: "/floorplans/LIME 21_CLASSIC_RH_02.05.2023.png",
  },
  {
    design: "Lime",
    label: "Lime 23",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "215.60",
    frontage: "8.99",
    url: "/floorplans/LIME 23_CLASSIC_RH_02.05.2023.png",
  },
  {
    design: "Lime",
    label: "Lime 25",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "234.87",
    frontage: "8.99",
    url: "/floorplans/LIME 25_CLASSIC_RH_02.05.2023.png",
  },
  {
    design: "Magenta",
    label: "Magenta 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "244.40",
    frontage: "16.95",
    url: "/floorplans/MAGENTA 26.png",
  },
  {
    design: "Magenta",
    label: "Magenta 29",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "271.52",
    frontage: "17.31",
    url: "/floorplans/MAGENTA 29.png",
  },
  {
    design: "Magenta",
    label: "Magenta 33",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "305.98",
    frontage: "18.24",
    url: "/floorplans/MAGENTA 33.png",
  },
  {
    design: "Magenta",
    label: "Magenta 36",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "334.09",
    frontage: "18.15",
    url: "/floorplans/MAGENTA 36.png",
  },
  {
    design: "Magnolia",
    label: "Magnolia 34",
    beds: "6",
    baths: "5",
    cars: "2",
    size: "312.02",
    frontage: "14.785",
    url: "/floorplans/MAGNOLIA 34_ CLASSIC_BROCHURE_17.04.2026.png",
  },
  {
    design: "Magnolia",
    label: "Magnolia 37",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "346.94",
    frontage: "14.785",
    url: "/floorplans/MAGNOLIA 37_ CLASSIC_BROCHURE_05.05.2026.png",
  },
  {
    design: "Magnolia",
    label: "Magnolia 43",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "395.28",
    frontage: "17.19",
    url: "/floorplans/MAGNOLIA 43_ CLASSIC_BROCHURE_20.12.24.png",
  },
  {
    design: "Magnolia",
    label: "Magnolia 45",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "419.08",
    frontage: "18.35",
    url: "/floorplans/MAGNOLIA 45_ CLASSIC_BROCHURE_20.12.24.png",
  },
  {
    design: "Magnolia",
    label: "Magnolia 47",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "432.50",
    frontage: "17.156",
    url: "/floorplans/MAGNOLIA 47.png",
  },
  {
    design: "Magnolia",
    label: "Magnolia 53",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "494.24",
    frontage: "19.07",
    url: "/floorplans/MAGNOLIA 53.png",
  },
  {
    design: "Mulberry",
    label: "Mulberry 22",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "208.66",
    frontage: "27.03",
    url: "/floorplans/MULBERRY 22_CLASSIC RH_BROCHURE_11.04.18.png",
  },
  {
    design: "Mulberry",
    label: "Mulberry 25",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "235.57",
    frontage: "27.51",
    url: "/floorplans/MULBERRY 25_CLASSIC RH_BROCHURE_06.06.19.png",
  },
  {
    design: "Mulberry",
    label: "Mulberry 25 (Alt Garage)",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "235.57",
    frontage: "27.51",
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mulberry25_garage.jpg",
  },
  {
    design: "Mulberry",
    label: "Mulberry 28",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "259.28",
    frontage: "29.67",
    url: "/floorplans/MULBERRY 28_CLASSIC RH_BROCHURE_11.04.18.png",
  },
  {
    design: "Mulberry",
    label: "Mulberry 28 (Bed 5)",
    beds: "5",
    baths: "2",
    cars: "2",
    size: "259.28",
    frontage: "29.67",
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mulberry28_bed-5.jpg",
  },
  {
    design: "Mulberry",
    label: "Mulberry 33",
    beds: "4",
    baths: "2.5",
    cars: "2",
    size: "307.82",
    frontage: "32.91",
    url: "/floorplans/MULBERRY 33_CLASSIC RH_BROCHURE_11.04.18.png",
  },
  {
    design: "Mulberry",
    label: "Mulberry 33 (Bed 5)",
    beds: "5",
    baths: "2.5",
    cars: "2",
    size: "307.82",
    frontage: "32.91",
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Mulberry33_bed-5.jpg",
  },
  {
    design: "Mulberry",
    label: "Mulberry 39",
    beds: "4",
    baths: "2.5",
    cars: "2",
    size: "365.23",
    frontage: "31.35",
    url: "/floorplans/MULBERRY 39_CLASSIC RH_BROCHURE_21.10.21.png",
  },
  {
    design: "Mahogany (QLD Only)",
    label: "Mahogany (QLD Only) 38",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "348.55",
    frontage: "14.15",
    url: "/floorplans/MAHOGANY 38_CLASSIC_RH_12.04.18.png",
  },
  {
    design: "Mahogany (QLD Only)",
    label: "Mahogany (QLD Only) 43",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "396.08",
    frontage: "14.05",
    url: "/floorplans/MAHOGANY 43_CLASSIC_RH_01.05.24.png",
  },
  {
    design: "Mahogany (QLD Only)",
    label: "Mahogany (QLD Only) 48",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "445.98",
    frontage: "15.01",
    url: "/floorplans/MAHOGANY 48_CLASSIC_RH_11.02.20.png",
  },
  {
    design: "Mahogany (QLD Only)",
    label: "Mahogany (QLD Only) 56",
    beds: "5",
    baths: "3",
    cars: "3",
    size: "51583",
    frontage: "18.13",
    url: "/floorplans/MAHOGANY 56.png",
  },
  {
    design: "Maize",
    label: "Maize 33",
    beds: "6",
    baths: "5",
    cars: "2",
    size: "310.96",
    frontage: "14.99",
    url: "/floorplans/MAIZE 33_ CLASSIC_BROCHURE_10.11.25.png",
  },
  {
    design: "Maize",
    label: "Maize 36",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "330.90",
    frontage: "14.99",
    url: "/floorplans/MAIZE 36_ CLASSIC_BROCHURE_10.11.25.png",
  },
  {
    design: "Maize",
    label: "Maize 40",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "369.42",
    frontage: "14.99",
    url: "/floorplans/MAIZE 40_ CLASSIC_BROCHURE_10.11.25.png",
  },
  {
    design: "Maize",
    label: "Maize 43",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "400.62",
    frontage: "15.47",
    url: "/floorplans/MAIZE 43_ CLASSIC_BROCHURE_10.11.25.png",
  },
  {
    design: "Maize",
    label: "Maize 47",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "440.64",
    frontage: "16.19",
    url: "/floorplans/MAIZE 47_CLASSIC_BROCHURE_10.11.25.png",
  },
  {
    design: "Maize",
    label: "Maize 54",
    beds: "8",
    baths: "5",
    cars: "2",
    size: "505.44",
    frontage: "16.19",
    url: "/floorplans/MAIZE 54.png",
  },
  {
    design: "Marigold",
    label: "Marigold 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "243.55",
    frontage: "11.39",
    url: "/floorplans/MARIGOLD 26_CLASSIC_LH_15.05.20.png",
  },
  {
    design: "Marigold",
    label: "Marigold 28",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "262.44",
    frontage: "12.47",
    url: "/floorplans/MARIGOLD 28_CLASSIC_LH_13.05.20.png",
  },
  {
    design: "Marigold",
    label: "Marigold 31",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "289.41",
    frontage: "12.95",
    url: "/floorplans/MARIGOLD 31_CLASSIC_LH_13.05.20.png",
  },
  {
    design: "Marigold",
    label: "Marigold 35",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "324.91",
    frontage: "12.95",
    url: "/floorplans/MARIGOLD 35_CLASSIC_LH_24.05.21.png",
  },
  {
    design: "Mauve",
    label: "Mauve 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "224.24",
    frontage: "13.91",
    url: "/floorplans/MAUVE 24.png",
  },
  {
    design: "Mauve",
    label: "Mauve 28",
    beds: "5",
    baths: "2",
    cars: "2",
    size: "259.24",
    frontage: "14.15",
    url: "/floorplans/MAUVE 28.png",
  },
  {
    design: "Mauve",
    label: "Mauve 32",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "298.07",
    frontage: "14.39",
    url: "/floorplans/MAUVE 32.png",
  },
  {
    design: "Mauve",
    label: "Mauve 35",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "328.66",
    frontage: "14.99",
    url: "/floorplans/MAUVE 35.png",
  },
  {
    design: "Mint",
    label: "Mint 17",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "158.74",
    frontage: "7.91",
    url: "/floorplans/MINT 17_CLASSIC_RH_02.05.2023.png",
  },
  {
    design: "Mint",
    label: "Mint 19",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "177.97",
    frontage: "7.91",
    url: "/floorplans/MINT 19_CLASSIC_RH_02.05.2023.png",
  },
  {
    design: "Mint",
    label: "Mint 21",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "191.33",
    frontage: "7.91",
    url: "/floorplans/MINT 21_CLASSIC_RH_02.05.2023.png",
  },
  {
    design: "Mint",
    label: "Mint 24",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "220.64",
    frontage: "7.91",
    url: "/floorplans/MINT 24_CLASSIC_RH_02.05.2023.png",
  },
  {
    design: "Mocha",
    label: "Mocha 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "225.93",
    frontage: "11.05",
    url: "/floorplans/MOCHA 24_CLASSIC_ATTACHED GARAGE_07.07.22.png",
  },
  {
    design: "Mocha",
    label: "Mocha 25",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "232.26",
    frontage: "13.93",
    url: "/floorplans/MOCHA 25_CLASSIC_13.09.19.png",
  },
  {
    design: "Mocha",
    label: "Mocha 28",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "260.09",
    frontage: "15.01",
    url: "/floorplans/MOCHA 28_CLASSIC_10.11.21.png",
  },
  {
    design: "Mocha",
    label: "Mocha 31",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "288.55",
    frontage: "14.29",
    url: "/floorplans/MOCHA 31_CLASSIC_13.12.19.png",
  },
  {
    design: "Mocha",
    label: "Mocha 35",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "321.36",
    frontage: "14.41",
    url: "/floorplans/MOCHA 35_CLASSIC_24.05.21.png",
  },
  {
    design: "Onyx",
    label: "Onyx 17",
    beds: "3",
    baths: "2",
    cars: "2",
    size: "160.38",
    frontage: "11.41",
    url: "/floorplans/ONYX 17.png",
  },
  {
    design: "Onyx",
    label: "Onyx 19",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "180.82",
    frontage: "11.89",
    url: "/floorplans/ONYX 19.png",
  },
  {
    design: "Onyx",
    label: "Onyx 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "198.23",
    frontage: "12.49",
    url: "/floorplans/ONYX 21.png",
  },
  {
    design: "Onyx",
    label: "Onyx 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "227.27",
    frontage: "13.09",
    url: "/floorplans/ONYX 24.png",
  },
  {
    design: "Orchid",
    label: "Orchid 23",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "209.52",
    frontage: "10.33",
    url: "/floorplans/ORCHID 23_CLASSIC_RH_BROCHURE_07.11.2022.png",
  },
  {
    design: "Orchid",
    label: "Orchid 25",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "228.94",
    frontage: "10.45",
    url: "/floorplans/ORCHID 25_CLASSIC_RH_BROCHURE_13.05.2020.png",
  },
  {
    design: "Orchid",
    label: "Orchid 29",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "268.18",
    frontage: "12.85",
    url: "/floorplans/ORCHID 29_CLASSIC_RH_BROCHURE_13.05.2020.png",
  },
  {
    design: "Orchid",
    label: "Orchid 34",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "315.08",
    frontage: "13.33",
    url: "/floorplans/ORCHID 34_CLASSIC_RH_BROCHURE_13.05.2020.png",
  },
  {
    design: "Quartz",
    label: "Quartz 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "199.69",
    frontage: "12.99",
    url: "/floorplans/QUARTZ 21_CLASSIC RH_BROCHURE_26.07.19.png",
  },
  {
    design: "Quartz",
    label: "Quartz 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "209.70",
    frontage: "12.99",
    url: "/floorplans/QUARTZ 23_CLASSIC RH_BROCHURE_28.03.19.png",
  },
  {
    design: "Quartz",
    label: "Quartz 25",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "228.39",
    frontage: "12.99",
    url: "/floorplans/QUARTZ 25_CLASSIC RH_BROCHURE_28.03.19.png",
  },
  {
    design: "Quartz",
    label: "Quartz 27",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "249.80",
    frontage: "12.99",
    url: "/floorplans/QUARTZ 27_CLASSIC RH_BROCHURE_17.04.26.png",
  },
  {
    design: "Robin",
    label: "Robin 5",
    beds: "3",
    baths: "2",
    cars: "1",
    size: "148.71",
    frontage: "13.94",
    url: "/floorplans/ROBIN 5.png",
  },
  {
    design: "Robin",
    label: "Robin 6",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "193.43",
    frontage: "13.84",
    url: "/floorplans/ROBIN 6.png",
  },
  {
    design: "Robin",
    label: "Robin 7",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "177.73",
    frontage: "13.00",
    url: "/floorplans/ROBIN 7.png",
  },
  {
    design: "Robin",
    label: "Robin 8",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "173.03",
    frontage: "10.27",
    url: "/floorplans/ROBIN 8.png",
  },
  {
    design: "Rose",
    label: "Rose 34",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "318.59",
    frontage: "17.53",
    url: "/floorplans/ROSE 34.png",
  },
  {
    design: "Rose",
    label: "Rose 38",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "354.91",
    frontage: "19.81",
    url: "/floorplans/ROSE 38.png",
  },
  {
    design: "Rose",
    label: "Rose 43",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "401.51",
    frontage: "19.81",
    url: "/floorplans/ROSE 43.png",
  },
  {
    design: "Rose",
    label: "Rose 53",
    beds: "4",
    baths: "3",
    cars: "3",
    size: "492.82",
    frontage: "22.69",
    url: "/floorplans/ROSE 53.png",
  },
  {
    design: "Rosewood",
    label: "Rosewood 23",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "212.95",
    frontage: "13.28",
    url: "/floorplans/ROSEWOOD 23.png",
  },
  {
    design: "Rosewood",
    label: "Rosewood 31",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "285.50",
    frontage: "13.86",
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2020/10/Screenshot-2026-01-06-at-11.18.44-AM.png",
  },
  {
    design: "Ruby",
    label: "Ruby 19",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "174.93",
    frontage: "7.83",
    url: "/floorplans/RUBY 19.png",
  },
  {
    design: "Ruby",
    label: "Ruby 21",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "195.51",
    frontage: "8.31",
    url: "/floorplans/RUBY 21.png",
  },
  {
    design: "Ruby",
    label: "Ruby 23",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "214.17",
    frontage: "9.03",
    url: "/floorplans/RUBY 23.png",
  },
  {
    design: "Ruby",
    label: "Ruby 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "251.38",
    frontage: "12.78",
    url: "/floorplans/RUBY 26.png",
  },
  {
    design: "Ruby",
    label: "Ruby 28",
    beds: "5",
    baths: "2",
    cars: "1",
    size: "263.37",
    frontage: "9.75",
    url: "/floorplans/RUBY 28.png",
  },
  {
    design: "Saffron",
    label: "Saffron 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "214.46",
    frontage: "13.23",
    url: "/floorplans/SAFFRON 23.png",
  },
  {
    design: "Saffron",
    label: "Saffron 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "245.88",
    frontage: "14.91",
    url: "/floorplans/SAFFRON 26.png",
  },
  {
    design: "Saffron",
    label: "Saffron 30",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "283.12",
    frontage: "17.19",
    url: "/floorplans/SAFFRON 30.png",
  },
  {
    design: "Saffron",
    label: "Saffron 35",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "320.98",
    frontage: "17.91",
    url: "/floorplans/SAFFRON 35.png",
  },
  {
    design: "Sienna",
    label: "Sienna 28",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "257.87",
    frontage: "14.91",
    url: "/floorplans/SIENNA 28.png",
  },
  {
    design: "Sienna",
    label: "Sienna 30",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "283.24",
    frontage: "17.07",
    url: "/floorplans/SIENNA 30.png",
  },
  {
    design: "Sienna",
    label: "Sienna 33",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "310.51",
    frontage: "17.31",
    url: "/floorplans/SIENNA 33.png",
  },
  {
    design: "Sienna",
    label: "Sienna 36",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "335.41",
    frontage: "17.55",
    url: "/floorplans/SIENNA 36.png",
  },
  {
    design: "Tangerine",
    label: "Tangerine 37",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "346.67",
    frontage: "13.81",
    url: "/floorplans/TANGERINE 37.png",
  },
  {
    design: "Tangerine",
    label: "Tangerine 41",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "383.40",
    frontage: "14.41",
    url: "/floorplans/TANGERINE 41.png",
  },
  {
    design: "Tangerine",
    label: "Tangerine 44",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "411.72",
    frontage: "15.01",
    url: "/floorplans/TANGERINE 44.png",
  },
  {
    design: "Tangerine",
    label: "Tangerine 49",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "451.78",
    frontage: "15.59",
    url: "/floorplans/TANGERINE 49.png",
  },
  {
    design: "Terracotta",
    label: "Terracotta 23",
    beds: "4",
    baths: "2",
    cars: "1",
    size: "211.58",
    frontage: "9.63",
    url: "/floorplans/TERRACOTTA 23.png",
  },
  {
    design: "Terracotta",
    label: "Terracotta 25",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "230.69",
    frontage: "10.31",
    url: "/floorplans/TERRACOTTA 25.png",
  },
  {
    design: "Terracotta",
    label: "Terracotta 30",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "282.01",
    frontage: "12.39",
    url: "/floorplans/TERRACOTTA 30.png",
  },
  {
    design: "Terracotta",
    label: "Terracotta 36",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "336.10",
    frontage: "12.99",
    url: "/floorplans/TERRACOTTA 36.png",
  },
  {
    design: "Tiffany",
    label: "Tiffany 22",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "203.97",
    frontage: "16.35",
    url: "/floorplans/TIFFANY 22.png",
  },
  {
    design: "Tiffany",
    label: "Tiffany 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "222.53",
    frontage: "17.31",
    url: "/floorplans/TIFFANY 24.png",
  },
  {
    design: "Tiffany",
    label: "Tiffany 27",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "252.45",
    frontage: "17.31",
    url: "/floorplans/TIFFANY 27.png",
  },
  {
    design: "Tiffany",
    label: "Tiffany 29",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "271.65",
    frontage: "17.31",
    url: "/floorplans/TIFFANY 29.png",
  },
  {
    design: "Topaz",
    label: "Topaz 21",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "199.37",
    frontage: "12.99",
    url: "/floorplans/TOPAZ 21.png",
  },
  {
    design: "Topaz",
    label: "Topaz 23",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "213.92",
    frontage: "13.47",
    url: "/floorplans/TOPAZ 23.png",
  },
  {
    design: "Topaz",
    label: "Topaz 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "239.47",
    frontage: "13.47",
    url: "/floorplans/TOPAZ 26.png",
  },
  {
    design: "Topaz",
    label: "Topaz 29",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "268.05",
    frontage: "14.67",
    url: "/floorplans/TOPAZ 29.png",
  },
  {
    design: "Turquoise",
    label: "Turquoise 24",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "222.13",
    frontage: "9.49",
    url: "/floorplans/TURQUOISE 24.png",
  },
  {
    design: "Turquoise",
    label: "Turquoise 25",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "235.31",
    frontage: "9.49",
    url: "/floorplans/TURQUOISE 25.png",
  },
  {
    design: "Turquoise",
    label: "Turquoise 26",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "244.98",
    frontage: "10.57",
    url: "/floorplans/TURQUOISE 26.png",
  },
  {
    design: "Turquoise",
    label: "Turquoise 28",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "263.24",
    frontage: "10.57",
    url: "/floorplans/TURQUOISE 28.png",
  },
  {
    design: "Turquoise",
    label: "Turquoise 31",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "290.14",
    frontage: "10.57",
    url: "/floorplans/TURQUOISE 31.png",
  },
  {
    design: "Violet",
    label: "Violet 33",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "309.3",
    frontage: "13.21",
    url: "/floorplans/VIOLET 33.png",
  },
  {
    design: "Violet",
    label: "Violet 40",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "372.44",
    frontage: "14.03",
    url: "/floorplans/VIOLET 40.png",
  },
  {
    design: "Violet",
    label: "Violet 45",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "415.04",
    frontage: "14.99",
    url: "/floorplans/VIOLET 45.png",
  },
  {
    design: "Violet",
    label: "Violet 48",
    beds: "4",
    baths: "4",
    cars: "2",
    size: "442.11",
    frontage: "14.99",
    url: "/floorplans/VIOLET 48.png",
  },
  {
    design: "Violet",
    label: "Violet 64",
    beds: "5",
    baths: "4",
    cars: "3",
    size: "586.61",
    frontage: "18.26",
    url: "/floorplans/VIOLET 64.png",
  },
  {
    design: "Viridian",
    label: "Viridian 28",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "264.05",
    frontage: "12.61",
    url: "/floorplans/VIRIDIAN 28.png",
  },
  {
    design: "Viridian",
    label: "Viridian 32",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "310.96",
    frontage: "12.65",
    url: "/floorplans/VIRIDIAN 32.png",
  },
  {
    design: "Viridian",
    label: "Viridian 39",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "360.85",
    frontage: "14.91",
    url: "/floorplans/VIRIDIAN 39.png",
  },
  {
    design: "Viridian",
    label: "Viridian 43",
    beds: "4",
    baths: "2",
    cars: "2",
    size: "400.00",
    frontage: "14.43",
    url: "/floorplans/VIRIDIAN 43.png",
  },
  {
    design: "Wisteria",
    label: "Wisteria 22",
    beds: "4",
    baths: "3",
    cars: "2",
    size: "201.45",
    frontage: "14.67",
    url: "/floorplans/WISTERIA 22_CLASSIC_BROCHURE_RH_03.03.2022.png",
  },
  {
    design: "Wisteria",
    label: "Wisteria 24 Mk II",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "226.25",
    frontage: "14.55",
    url: "/floorplans/WISTERIA 24.png",
  },
  {
    design: "Wisteria",
    label: "Wisteria 26",
    beds: "5",
    baths: "3",
    cars: "2",
    size: "240.79",
    frontage: "12.47",
    url: "/floorplans/WISTERIA 26.png",
  },
  {
    design: "Wisteria",
    label: "Wisteria 29",
    beds: "6",
    baths: "4",
    cars: "2",
    size: "267.82",
    frontage: "20.09",
    url: "https://www.hudsonhomes.com.au/wp-content/uploads/2019/02/Screenshot-2026-01-06-at-10.40.08-AM.png",
  },
];
