export interface EstatePodRule {
  id: string;
  estateName: string;
  developer: string;
  council: string;
  suburb: string;
  frontSetbackOmpM: number; // Front setback to building line / OMP (e.g. 3.0m)
  frontSetbackGarageM: number; // Front setback to garage door (e.g. 5.0m or 5.5m)
  sideSetbackStandardM: number; // Standard non-BTB side setback (e.g. 1.0m or 1.25m)
  sideSetbackBtbM: number; // Built to Boundary offset (e.g. 0.2m / 200mm clearance)
  rearSetbackM: number; // Rear setback (e.g. 1.5m or 2.0m)
  secondaryStreetSetbackM: number; // Corner lot secondary street (e.g. 2.0m)
  maxSiteCoveragePct: number; // Maximum building footprint % of lot (e.g. 50% or 60%)
  maxBuildingHeightM: number;
  notes: string;
}

export const QUEENSLAND_ESTATE_POD_PRESETS: EstatePodRule[] = [
  {
    id: "flagstone",
    estateName: "Flagstone Estate",
    developer: "Peet",
    council: "Logan City Council",
    suburb: "Flagstone",
    frontSetbackOmpM: 3.0,
    frontSetbackGarageM: 5.0,
    sideSetbackStandardM: 1.0,
    sideSetbackBtbM: 0.2, // 200mm to boundary
    rearSetbackM: 1.0,
    secondaryStreetSetbackM: 2.0,
    maxSiteCoveragePct: 60,
    maxBuildingHeightM: 8.5,
    notes: "3.0m OMP, 5.0m garage, 1.0m side & rear. BTB garage allowed with 200mm offset.",
  },
  {
    id: "providence",
    estateName: "Providence Estate",
    developer: "Stockland",
    council: "Ipswich City Council",
    suburb: "South Ripley",
    frontSetbackOmpM: 3.0,
    frontSetbackGarageM: 5.4,
    sideSetbackStandardM: 1.0,
    sideSetbackBtbM: 0.2,
    rearSetbackM: 1.5,
    secondaryStreetSetbackM: 2.0,
    maxSiteCoveragePct: 55,
    maxBuildingHeightM: 8.5,
    notes: "3.0m OMP, 5.4m garage, 1.0m side, 1.5m rear. Max 55% site coverage.",
  },
  {
    id: "yarrabilba",
    estateName: "Yarrabilba",
    developer: "Lendlease",
    council: "Logan City Council",
    suburb: "Yarrabilba",
    frontSetbackOmpM: 3.0,
    frontSetbackGarageM: 5.0,
    sideSetbackStandardM: 1.0,
    sideSetbackBtbM: 0.2,
    rearSetbackM: 1.5,
    secondaryStreetSetbackM: 2.0,
    maxSiteCoveragePct: 60,
    maxBuildingHeightM: 8.5,
    notes: "3.0m OMP, 5.0m garage, 1.0m side, 1.5m rear.",
  },
  {
    id: "springfield_rise",
    estateName: "Springfield Rise",
    developer: "Lendlease",
    council: "Ipswich City Council",
    suburb: "Springfield",
    frontSetbackOmpM: 4.0,
    frontSetbackGarageM: 5.5,
    sideSetbackStandardM: 1.25,
    sideSetbackBtbM: 0.2,
    rearSetbackM: 2.0,
    secondaryStreetSetbackM: 2.5,
    maxSiteCoveragePct: 50,
    maxBuildingHeightM: 8.5,
    notes: "4.0m OMP, 5.5m garage, 1.25m side, 2.0m rear.",
  },
  {
    id: "harmony",
    estateName: "Harmony",
    developer: "AVID Property Group",
    council: "Sunshine Coast Council",
    suburb: "Palmview",
    frontSetbackOmpM: 3.0,
    frontSetbackGarageM: 5.0,
    sideSetbackStandardM: 1.0,
    sideSetbackBtbM: 0.2,
    rearSetbackM: 1.5,
    secondaryStreetSetbackM: 2.0,
    maxSiteCoveragePct: 55,
    maxBuildingHeightM: 8.5,
    notes: "3.0m OMP, 5.0m garage, 1.0m side, 1.5m rear. Max 55% coverage.",
  },
  {
    id: "north_harbour",
    estateName: "North Harbour",
    developer: "North Harbour Holdings",
    council: "City of Moreton Bay",
    suburb: "Burpengary East",
    frontSetbackOmpM: 4.0,
    frontSetbackGarageM: 5.5,
    sideSetbackStandardM: 1.0,
    sideSetbackBtbM: 0.2,
    rearSetbackM: 1.5,
    secondaryStreetSetbackM: 2.0,
    maxSiteCoveragePct: 50,
    maxBuildingHeightM: 8.5,
    notes: "4.0m OMP, 5.5m garage, 1.0m side, 1.5m rear.",
  },
  {
    id: "shoreline",
    estateName: "Shoreline",
    developer: "Lendlease",
    council: "Redland City Council",
    suburb: "Redland Bay",
    frontSetbackOmpM: 3.0,
    frontSetbackGarageM: 5.0,
    sideSetbackStandardM: 1.0,
    sideSetbackBtbM: 0.2,
    rearSetbackM: 1.5,
    secondaryStreetSetbackM: 2.0,
    maxSiteCoveragePct: 55,
    maxBuildingHeightM: 8.5,
    notes: "Bayside POD with 3.0m OMP, 5.0m garage, 1.0m side.",
  },
  {
    id: "covella",
    estateName: "Covella",
    developer: "AVID Property Group",
    council: "Logan City Council",
    suburb: "Greenbank",
    frontSetbackOmpM: 4.0,
    frontSetbackGarageM: 5.5,
    sideSetbackStandardM: 1.25,
    sideSetbackBtbM: 0.2,
    rearSetbackM: 2.0,
    secondaryStreetSetbackM: 2.5,
    maxSiteCoveragePct: 50,
    maxBuildingHeightM: 8.5,
    notes: "Acreage & standard residential mix with 4.0m OMP, 5.5m garage.",
  },
  {
    id: "qdc_default",
    estateName: "General QLD Residential (QDC MP 1.1 / 1.2)",
    developer: "Queensland Development Code",
    council: "All QLD Councils",
    suburb: "Queensland",
    frontSetbackOmpM: 4.0,
    frontSetbackGarageM: 5.5,
    sideSetbackStandardM: 1.0,
    sideSetbackBtbM: 0.2,
    rearSetbackM: 1.5,
    secondaryStreetSetbackM: 2.0,
    maxSiteCoveragePct: 50,
    maxBuildingHeightM: 8.5,
    notes: "Default Queensland statutory setback benchmarks.",
  },
];
