/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CropperRouteImport } from './routes/cropper'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedFloorplanEditorRouteImport } from './routes/_authenticated/floorplan-editor'
import { Route as AuthenticatedFlyerRouteImport } from './routes/_authenticated/flyer'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedQuoteBuilderRouteImport } from './routes/_authenticated/quote-builder'
import { Route as AuthenticatedTenderRequestRouteImport } from './routes/_authenticated/tender-request'
import { Route as BrowseLandRouteImport } from './routes/browse/land'
import { Route as BrowsePackagesRouteImport } from './routes/browse/packages'
import { Route as CIdRouteImport } from './routes/c/$id'
import { Route as PackageIdRouteImport } from './routes/package/$id'
import { Route as QuoteIdRouteImport } from './routes/quote/$id'
import { Route as TenderDraftingIdRouteImport } from './routes/tender-drafting/$id'
import { Route as TenderSignIdRouteImport } from './routes/tender-sign/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CropperRoute = CropperRouteImport.update({
  id: '/cropper',
  path: '/cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFloorplanEditorRoute =
  AuthenticatedFloorplanEditorRouteImport.update({
    id: '/floorplan-editor',
    path: '/floorplan-editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFlyerRoute = AuthenticatedFlyerRouteImport.update({
  id: '/flyer',
  path: '/flyer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuoteBuilderRoute =
  AuthenticatedQuoteBuilderRouteImport.update({
    id: '/quote-builder',
    path: '/quote-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTenderRequestRoute =
  AuthenticatedTenderRequestRouteImport.update({
    id: '/tender-request',
    path: '/tender-request',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const BrowseLandRoute = BrowseLandRouteImport.update({
  id: '/browse/land',
  path: '/browse/land',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePackagesRoute = BrowsePackagesRouteImport.update({
  id: '/browse/packages',
  path: '/browse/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const CIdRoute = CIdRouteImport.update({
  id: '/c/$id',
  path: '/c/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdRoute = PackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderDraftingIdRoute = TenderDraftingIdRouteImport.update({
  id: '/tender-drafting/$id',
  path: '/tender-drafting/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderSignIdRoute = TenderSignIdRouteImport.update({
  id: '/tender-sign/$id',
  path: '/tender-sign/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cropper': typeof CropperRoute
  '/kiosk': typeof KioskRoute
  '/pay': typeof PayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/floorplan-editor': typeof AuthenticatedFloorplanEditorRoute
  '/flyer': typeof AuthenticatedFlyerRoute
  '/hub': typeof AuthenticatedHubRoute
  '/quote-builder': typeof AuthenticatedQuoteBuilderRoute
  '/tender-request': typeof AuthenticatedTenderRequestRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/c/$id': typeof CIdRoute
  '/package/$id': typeof PackageIdRoute
  '/quote/$id': typeof QuoteIdRoute
  '/tender-drafting/$id': typeof TenderDraftingIdRoute
  '/tender-sign/$id': typeof TenderSignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cropper': typeof CropperRoute
  '/kiosk': typeof KioskRoute
  '/pay': typeof PayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/floorplan-editor': typeof AuthenticatedFloorplanEditorRoute
  '/flyer': typeof AuthenticatedFlyerRoute
  '/hub': typeof AuthenticatedHubRoute
  '/quote-builder': typeof AuthenticatedQuoteBuilderRoute
  '/tender-request': typeof AuthenticatedTenderRequestRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/c/$id': typeof CIdRoute
  '/package/$id': typeof PackageIdRoute
  '/quote/$id': typeof QuoteIdRoute
  '/tender-drafting/$id': typeof TenderDraftingIdRoute
  '/tender-sign/$id': typeof TenderSignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cropper': typeof CropperRoute
  '/kiosk': typeof KioskRoute
  '/pay': typeof PayRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/floorplan-editor': typeof AuthenticatedFloorplanEditorRoute
  '/_authenticated/flyer': typeof AuthenticatedFlyerRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/quote-builder': typeof AuthenticatedQuoteBuilderRoute
  '/_authenticated/tender-request': typeof AuthenticatedTenderRequestRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/c/$id': typeof CIdRoute
  '/package/$id': typeof PackageIdRoute
  '/quote/$id': typeof QuoteIdRoute
  '/tender-drafting/$id': typeof TenderDraftingIdRoute
  '/tender-sign/$id': typeof TenderSignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cropper'
    | '/kiosk'
    | '/pay'
    | '/reset-password'
    | '/crm'
    | '/database'
    | '/floorplan-editor'
    | '/flyer'
    | '/hub'
    | '/quote-builder'
    | '/tender-request'
    | '/browse/land'
    | '/browse/packages'
    | '/c/$id'
    | '/package/$id'
    | '/quote/$id'
    | '/tender-drafting/$id'
    | '/tender-sign/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cropper'
    | '/kiosk'
    | '/pay'
    | '/reset-password'
    | '/crm'
    | '/database'
    | '/floorplan-editor'
    | '/flyer'
    | '/hub'
    | '/quote-builder'
    | '/tender-request'
    | '/browse/land'
    | '/browse/packages'
    | '/c/$id'
    | '/package/$id'
    | '/quote/$id'
    | '/tender-drafting/$id'
    | '/tender-sign/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cropper'
    | '/kiosk'
    | '/pay'
    | '/reset-password'
    | '/_authenticated/crm'
    | '/_authenticated/database'
    | '/_authenticated/floorplan-editor'
    | '/_authenticated/flyer'
    | '/_authenticated/hub'
    | '/_authenticated/quote-builder'
    | '/_authenticated/tender-request'
    | '/browse/land'
    | '/browse/packages'
    | '/c/$id'
    | '/package/$id'
    | '/quote/$id'
    | '/tender-drafting/$id'
    | '/tender-sign/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CropperRoute: typeof CropperRoute
  KioskRoute: typeof KioskRoute
  PayRoute: typeof PayRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BrowseLandRoute: typeof BrowseLandRoute
  BrowsePackagesRoute: typeof BrowsePackagesRoute
  CIdRoute: typeof CIdRoute
  PackageIdRoute: typeof PackageIdRoute
  QuoteIdRoute: typeof QuoteIdRoute
  TenderDraftingIdRoute: typeof TenderDraftingIdRoute
  TenderSignIdRoute: typeof TenderSignIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cropper': {
      id: '/cropper'
      path: '/cropper'
      fullPath: '/cropper'
      preLoaderRoute: typeof CropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/floorplan-editor': {
      id: '/_authenticated/floorplan-editor'
      path: '/floorplan-editor'
      fullPath: '/floorplan-editor'
      preLoaderRoute: typeof AuthenticatedFloorplanEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flyer': {
      id: '/_authenticated/flyer'
      path: '/flyer'
      fullPath: '/flyer'
      preLoaderRoute: typeof AuthenticatedFlyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quote-builder': {
      id: '/_authenticated/quote-builder'
      path: '/quote-builder'
      fullPath: '/quote-builder'
      preLoaderRoute: typeof AuthenticatedQuoteBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tender-request': {
      id: '/_authenticated/tender-request'
      path: '/tender-request'
      fullPath: '/tender-request'
      preLoaderRoute: typeof AuthenticatedTenderRequestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/browse/land': {
      id: '/browse/land'
      path: '/browse/land'
      fullPath: '/browse/land'
      preLoaderRoute: typeof BrowseLandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/packages': {
      id: '/browse/packages'
      path: '/browse/packages'
      fullPath: '/browse/packages'
      preLoaderRoute: typeof BrowsePackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$id': {
      id: '/c/$id'
      path: '/c/$id'
      fullPath: '/c/$id'
      preLoaderRoute: typeof CIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id': {
      id: '/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof PackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-drafting/$id': {
      id: '/tender-drafting/$id'
      path: '/tender-drafting/$id'
      fullPath: '/tender-drafting/$id'
      preLoaderRoute: typeof TenderDraftingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-sign/$id': {
      id: '/tender-sign/$id'
      path: '/tender-sign/$id'
      fullPath: '/tender-sign/$id'
      preLoaderRoute: typeof TenderSignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedFloorplanEditorRoute: typeof AuthenticatedFloorplanEditorRoute
  AuthenticatedFlyerRoute: typeof AuthenticatedFlyerRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedQuoteBuilderRoute: typeof AuthenticatedQuoteBuilderRoute
  AuthenticatedTenderRequestRoute: typeof AuthenticatedTenderRequestRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedFloorplanEditorRoute: AuthenticatedFloorplanEditorRoute,
  AuthenticatedFlyerRoute: AuthenticatedFlyerRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedQuoteBuilderRoute: AuthenticatedQuoteBuilderRoute,
  AuthenticatedTenderRequestRoute: AuthenticatedTenderRequestRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CropperRoute: CropperRoute,
  KioskRoute: KioskRoute,
  PayRoute: PayRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BrowseLandRoute: BrowseLandRoute,
  BrowsePackagesRoute: BrowsePackagesRoute,
  CIdRoute: CIdRoute,
  PackageIdRoute: PackageIdRoute,
  QuoteIdRoute: QuoteIdRoute,
  TenderDraftingIdRoute: TenderDraftingIdRoute,
  TenderSignIdRoute: TenderSignIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
