/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CropperRouteImport } from './routes/cropper'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedFlyerRouteImport } from './routes/_authenticated/flyer'
import { Route as BrowseLandRouteImport } from './routes/browse/land'
import { Route as BrowsePackagesRouteImport } from './routes/browse/packages'
import { Route as PackageIdRouteImport } from './routes/package/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CropperRoute = CropperRouteImport.update({
  id: '/cropper',
  path: '/cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlyerRoute = AuthenticatedFlyerRouteImport.update({
  id: '/flyer',
  path: '/flyer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BrowseLandRoute = BrowseLandRouteImport.update({
  id: '/browse/land',
  path: '/browse/land',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePackagesRoute = BrowsePackagesRouteImport.update({
  id: '/browse/packages',
  path: '/browse/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdRoute = PackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cropper': typeof CropperRoute
  '/reset-password': typeof ResetPasswordRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/flyer': typeof AuthenticatedFlyerRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/package/$id': typeof PackageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cropper': typeof CropperRoute
  '/reset-password': typeof ResetPasswordRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/flyer': typeof AuthenticatedFlyerRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/package/$id': typeof PackageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/cropper': typeof CropperRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/flyer': typeof AuthenticatedFlyerRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/package/$id': typeof PackageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cropper'
    | '/reset-password'
    | '/database'
    | '/flyer'
    | '/browse/land'
    | '/browse/packages'
    | '/package/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cropper'
    | '/reset-password'
    | '/database'
    | '/flyer'
    | '/browse/land'
    | '/browse/packages'
    | '/package/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/cropper'
    | '/reset-password'
    | '/_authenticated/database'
    | '/_authenticated/flyer'
    | '/browse/land'
    | '/browse/packages'
    | '/package/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CropperRoute: typeof CropperRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BrowseLandRoute: typeof BrowseLandRoute
  BrowsePackagesRoute: typeof BrowsePackagesRoute
  PackageIdRoute: typeof PackageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cropper': {
      id: '/cropper'
      path: '/cropper'
      fullPath: '/cropper'
      preLoaderRoute: typeof CropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flyer': {
      id: '/_authenticated/flyer'
      path: '/flyer'
      fullPath: '/flyer'
      preLoaderRoute: typeof AuthenticatedFlyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/browse/land': {
      id: '/browse/land'
      path: '/browse/land'
      fullPath: '/browse/land'
      preLoaderRoute: typeof BrowseLandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/packages': {
      id: '/browse/packages'
      path: '/browse/packages'
      fullPath: '/browse/packages'
      preLoaderRoute: typeof BrowsePackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id': {
      id: '/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof PackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedFlyerRoute: typeof AuthenticatedFlyerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedFlyerRoute: AuthenticatedFlyerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CropperRoute: CropperRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BrowseLandRoute: BrowseLandRoute,
  BrowsePackagesRoute: BrowsePackagesRoute,
  PackageIdRoute: PackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
