/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedDatabaseRouteImport } from './routes/_authenticated/database'
import { Route as AuthenticatedFlyerRouteImport } from './routes/_authenticated/flyer'
import { Route as ApiEnhanceImageRouteImport } from './routes/api/enhance-image'
import { Route as ApiFloorplanImageRouteImport } from './routes/api/floorplan-image'
import { Route as ApiGarageDimsRouteImport } from './routes/api/garage-dims'
import { Route as ApiParseLotListRouteImport } from './routes/api/parse-lot-list'
import { Route as ApiPlanRoomsRouteImport } from './routes/api/plan-rooms'
import { Route as ApiWidenFacadeRouteImport } from './routes/api/widen-facade'
import { Route as BrowseLandRouteImport } from './routes/browse/land'
import { Route as BrowsePackagesRouteImport } from './routes/browse/packages'
import { Route as PackageIdRouteImport } from './routes/package/$id'
import { Route as ApiFacadeImageIdRouteImport } from './routes/api/facade-image.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDatabaseRoute = AuthenticatedDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFlyerRoute = AuthenticatedFlyerRouteImport.update({
  id: '/flyer',
  path: '/flyer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiEnhanceImageRoute = ApiEnhanceImageRouteImport.update({
  id: '/api/enhance-image',
  path: '/api/enhance-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFloorplanImageRoute = ApiFloorplanImageRouteImport.update({
  id: '/api/floorplan-image',
  path: '/api/floorplan-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGarageDimsRoute = ApiGarageDimsRouteImport.update({
  id: '/api/garage-dims',
  path: '/api/garage-dims',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiParseLotListRoute = ApiParseLotListRouteImport.update({
  id: '/api/parse-lot-list',
  path: '/api/parse-lot-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanRoomsRoute = ApiPlanRoomsRouteImport.update({
  id: '/api/plan-rooms',
  path: '/api/plan-rooms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidenFacadeRoute = ApiWidenFacadeRouteImport.update({
  id: '/api/widen-facade',
  path: '/api/widen-facade',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseLandRoute = BrowseLandRouteImport.update({
  id: '/browse/land',
  path: '/browse/land',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowsePackagesRoute = BrowsePackagesRouteImport.update({
  id: '/browse/packages',
  path: '/browse/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdRoute = PackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFacadeImageIdRoute = ApiFacadeImageIdRouteImport.update({
  id: '/api/facade-image/$id',
  path: '/api/facade-image/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/flyer': typeof AuthenticatedFlyerRoute
  '/api/enhance-image': typeof ApiEnhanceImageRoute
  '/api/floorplan-image': typeof ApiFloorplanImageRoute
  '/api/garage-dims': typeof ApiGarageDimsRoute
  '/api/parse-lot-list': typeof ApiParseLotListRoute
  '/api/plan-rooms': typeof ApiPlanRoomsRoute
  '/api/widen-facade': typeof ApiWidenFacadeRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/package/$id': typeof PackageIdRoute
  '/api/facade-image/$id': typeof ApiFacadeImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/database': typeof AuthenticatedDatabaseRoute
  '/flyer': typeof AuthenticatedFlyerRoute
  '/api/enhance-image': typeof ApiEnhanceImageRoute
  '/api/floorplan-image': typeof ApiFloorplanImageRoute
  '/api/garage-dims': typeof ApiGarageDimsRoute
  '/api/parse-lot-list': typeof ApiParseLotListRoute
  '/api/plan-rooms': typeof ApiPlanRoomsRoute
  '/api/widen-facade': typeof ApiWidenFacadeRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/package/$id': typeof PackageIdRoute
  '/api/facade-image/$id': typeof ApiFacadeImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/database': typeof AuthenticatedDatabaseRoute
  '/_authenticated/flyer': typeof AuthenticatedFlyerRoute
  '/api/enhance-image': typeof ApiEnhanceImageRoute
  '/api/floorplan-image': typeof ApiFloorplanImageRoute
  '/api/garage-dims': typeof ApiGarageDimsRoute
  '/api/parse-lot-list': typeof ApiParseLotListRoute
  '/api/plan-rooms': typeof ApiPlanRoomsRoute
  '/api/widen-facade': typeof ApiWidenFacadeRoute
  '/browse/land': typeof BrowseLandRoute
  '/browse/packages': typeof BrowsePackagesRoute
  '/package/$id': typeof PackageIdRoute
  '/api/facade-image/$id': typeof ApiFacadeImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/database'
    | '/flyer'
    | '/api/enhance-image'
    | '/api/floorplan-image'
    | '/api/garage-dims'
    | '/api/parse-lot-list'
    | '/api/plan-rooms'
    | '/api/widen-facade'
    | '/browse/land'
    | '/browse/packages'
    | '/package/$id'
    | '/api/facade-image/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/database'
    | '/flyer'
    | '/api/enhance-image'
    | '/api/floorplan-image'
    | '/api/garage-dims'
    | '/api/parse-lot-list'
    | '/api/plan-rooms'
    | '/api/widen-facade'
    | '/browse/land'
    | '/browse/packages'
    | '/package/$id'
    | '/api/facade-image/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/database'
    | '/_authenticated/flyer'
    | '/api/enhance-image'
    | '/api/floorplan-image'
    | '/api/garage-dims'
    | '/api/parse-lot-list'
    | '/api/plan-rooms'
    | '/api/widen-facade'
    | '/browse/land'
    | '/browse/packages'
    | '/package/$id'
    | '/api/facade-image/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiEnhanceImageRoute: typeof ApiEnhanceImageRoute
  ApiFloorplanImageRoute: typeof ApiFloorplanImageRoute
  ApiGarageDimsRoute: typeof ApiGarageDimsRoute
  ApiParseLotListRoute: typeof ApiParseLotListRoute
  ApiPlanRoomsRoute: typeof ApiPlanRoomsRoute
  ApiWidenFacadeRoute: typeof ApiWidenFacadeRoute
  BrowseLandRoute: typeof BrowseLandRoute
  BrowsePackagesRoute: typeof BrowsePackagesRoute
  PackageIdRoute: typeof PackageIdRoute
  ApiFacadeImageIdRoute: typeof ApiFacadeImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/database': {
      id: '/_authenticated/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AuthenticatedDatabaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/flyer': {
      id: '/_authenticated/flyer'
      path: '/flyer'
      fullPath: '/flyer'
      preLoaderRoute: typeof AuthenticatedFlyerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/enhance-image': {
      id: '/api/enhance-image'
      path: '/api/enhance-image'
      fullPath: '/api/enhance-image'
      preLoaderRoute: typeof ApiEnhanceImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/floorplan-image': {
      id: '/api/floorplan-image'
      path: '/api/floorplan-image'
      fullPath: '/api/floorplan-image'
      preLoaderRoute: typeof ApiFloorplanImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/garage-dims': {
      id: '/api/garage-dims'
      path: '/api/garage-dims'
      fullPath: '/api/garage-dims'
      preLoaderRoute: typeof ApiGarageDimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/parse-lot-list': {
      id: '/api/parse-lot-list'
      path: '/api/parse-lot-list'
      fullPath: '/api/parse-lot-list'
      preLoaderRoute: typeof ApiParseLotListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plan-rooms': {
      id: '/api/plan-rooms'
      path: '/api/plan-rooms'
      fullPath: '/api/plan-rooms'
      preLoaderRoute: typeof ApiPlanRoomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widen-facade': {
      id: '/api/widen-facade'
      path: '/api/widen-facade'
      fullPath: '/api/widen-facade'
      preLoaderRoute: typeof ApiWidenFacadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/land': {
      id: '/browse/land'
      path: '/browse/land'
      fullPath: '/browse/land'
      preLoaderRoute: typeof BrowseLandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/packages': {
      id: '/browse/packages'
      path: '/browse/packages'
      fullPath: '/browse/packages'
      preLoaderRoute: typeof BrowsePackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id': {
      id: '/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof PackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/facade-image/$id': {
      id: '/api/facade-image/$id'
      path: '/api/facade-image/$id'
      fullPath: '/api/facade-image/$id'
      preLoaderRoute: typeof ApiFacadeImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDatabaseRoute: typeof AuthenticatedDatabaseRoute
  AuthenticatedFlyerRoute: typeof AuthenticatedFlyerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDatabaseRoute: AuthenticatedDatabaseRoute,
  AuthenticatedFlyerRoute: AuthenticatedFlyerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiEnhanceImageRoute: ApiEnhanceImageRoute,
  ApiFloorplanImageRoute: ApiFloorplanImageRoute,
  ApiGarageDimsRoute: ApiGarageDimsRoute,
  ApiParseLotListRoute: ApiParseLotListRoute,
  ApiPlanRoomsRoute: ApiPlanRoomsRoute,
  ApiWidenFacadeRoute: ApiWidenFacadeRoute,
  BrowseLandRoute: BrowseLandRoute,
  BrowsePackagesRoute: BrowsePackagesRoute,
  PackageIdRoute: PackageIdRoute,
  ApiFacadeImageIdRoute: ApiFacadeImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
