import type { CatalogueCategory, CatalogueItem } from "./quoteTypes";

export const DEFAULT_CUSTOM_RATES = {
  singleGroundLivingM2Rate: 1660,
  singleGroundLivingH3M2Rate: 1810,
  doubleGroundLivingM2Rate: 1500,
  doubleUpperLivingM2Rate: 1800,
  doubleGroundLivingH3M2Rate: 1650,
  doubleUpperLivingH3M2Rate: 1950,
  garageM2Rate: 1400,
  ancillaryM2Rate: 869, // Alfresco, Porch
  doubleScaffoldingAllowance: 8500,
};

export const CATEGORY_LABELS: Record<CatalogueCategory, string> = {
  structural: "Structural Modifications",
  doors_windows: "Doors and Windows",
  external: "Floorplan & External",
  internal_kitchen: "Internal - Kitchen",
  internal_bathroom: "Internal - Bathroom",
  internal_bedrooms: "Internal - Bedrooms & Storage",
  internal_laundry: "Internal - Laundry",
  colour_upgrades: "Electrical, HVAC & Finishes",
  site_earthworks: "Site Specific & Engineering Reports",
  council_statutory: "Council & Statutory Requirements",
};

export interface DuplicateGroup {
  primaryItem: CatalogueItem;
  relatedItems: CatalogueItem[];
  matchReason: string;
}

/**
 * Automatically flags potential duplicate or overlapping items in the catalogue.
 * Compares names, categories, and high-specificity keywords (e.g. Flood, Town Planning, Traffic, Cooktop, etc.).
 */
export function findPotentialDuplicates(items: CatalogueItem[]): DuplicateGroup[] {
  const clean = (s: string) =>
    s
      .toLowerCase()
      .replace(/[^a-z0-9]/g, " ")
      .trim();

  const STOP_WORDS = new Set([
    "allowance", "provide", "standard", "upgrade", "storey", "single", "double",
    "inclusions", "range", "with", "from", "level", "living", "area", "custom",
    "floor", "plasterboard", "concrete", "steel", "doors", "windows", "internal",
    "external", "additional", "house", "slab", "height", "timber", "framing",
    "finish", "lining", "linings", "line", "report", "package", "system", "wall",
    "ceiling", "ceilings", "ground", "first", "upper", "footprint", "under", "roof",
    "roofline", "builder", "specification", "luxury", "tiles", "tiled", "ceramic",
    "throughout", "structure", "engineered", "engineering", "architectural", "unit"
  ]);

  const groups: DuplicateGroup[] = [];
  const processedPairs = new Set<string>();

  for (let i = 0; i < items.length; i++) {
    const a = items[i];
    const wordsA = new Set(
      clean(a.name)
        .split(/\s+/)
        .filter((w) => w.length > 2 && !STOP_WORDS.has(w)),
    );
    const related: CatalogueItem[] = [];
    let matchReason = "";

    for (let j = 0; j < items.length; j++) {
      if (i === j) continue;
      const b = items[j];
      const pairKey = [a.id, b.id].sort().join("::");

      // Check 1: Exact / near exact name
      if (clean(a.name) === clean(b.name)) {
        if (!processedPairs.has(pairKey)) {
          related.push(b);
          matchReason = "Identical item name";
          processedPairs.add(pairKey);
        }
        continue;
      }

      // Check 2: Same category keyword overlap with specific terms
      if (a.category === b.category) {
        const wordsB = clean(b.name)
          .split(/\s+/)
          .filter((w) => w.length > 2 && !STOP_WORDS.has(w));
        const commonWords = wordsB.filter((w) => wordsA.has(w));

        const HIGH_SPECIFICITY_KEYWORDS = [
          "flood", "traffic", "cooktop", "rangehood", "covenant", "demolition",
          "acoustic", "bushfire", "elevator", "lodgement", "planner", "assessment",
          "pedestrian", "asbestos", "rock", "breaker", "potholing", "cctv", "hstp",
          "sewer", "survey", "pegs", "balcony", "alfresco", "theatre", "pool", "piering",
          "sliding", "stacker", "security", "screen", "oven", "fridge", "cupboards",
          "stone", "benchtop", "sink", "ensuite", "tiles", "robe", "shelving",
          "3phase", "charger", "aircon", "solar", "battery", "epoxy", "render", "driveway", "turf"
        ];

        const matchedHighSpec = commonWords.filter((w) => HIGH_SPECIFICITY_KEYWORDS.includes(w));

        if (commonWords.length >= 2 || matchedHighSpec.length >= 1) {
          if (!processedPairs.has(pairKey)) {
            related.push(b);
            matchReason = `Related item sharing terms: "${commonWords.join(", ")}"`;
            processedPairs.add(pairKey);
          }
        }
      }
    }

    if (related.length > 0) {
      groups.push({
        primaryItem: a,
        relatedItems: related,
        matchReason,
      });
    }
  }

  return groups;
}

/**
 * Master Hudson Homes Price Catalogue
 * Pre-populated with professional, client-friendly construction descriptions and standard rates.
 * All items and wording are fully editable in the Admin Catalogue modal.
 */
export const DEFAULT_CATALOGUE: CatalogueItem[] = [
  // ==========================================
  // 1. STRUCTURAL MODIFICATIONS
  // ==========================================
  {
    id: "str_raked_ceiling",
    category: "structural",
    name: "Raked Ceiling with Engineered Trusses",
    description: "Architectural pitched raked ceiling structure with engineered scissor trusses to selected living areas in lieu of standard flat ceiling.",
    unitType: "per_m2",
    unitRate: 310,
    isClientSelectable: true,
  },
  {
    id: "str_custom_ss_h2",
    category: "structural",
    name: "Custom Single Storey Living Area (H2 Inclusions)",
    description: "Custom ground floor enclosed living area framing, insulation, plasterboard, and finishes based on H2 Builder specification.",
    unitType: "per_m2",
    unitRate: 1660,
    isClientSelectable: true,
  },
  {
    id: "str_custom_ss_h3",
    category: "structural",
    name: "Custom Single Storey Living Area (H3 Inclusions)",
    description: "Custom ground floor enclosed living area framing, insulation, plasterboard, and finishes based on H3 Luxury specification.",
    unitType: "per_m2",
    unitRate: 1810,
    isClientSelectable: true,
  },
  {
    id: "str_custom_garage",
    category: "structural",
    name: "Custom Garage Floor Footprint Extension",
    description: "Reinforced concrete slab, timber/steel wall framing, exterior brickwork/cladding, and engineered roof trusses for garage.",
    unitType: "per_m2",
    unitRate: 1400,
    isClientSelectable: true,
  },
  {
    id: "str_custom_porch_alfresco",
    category: "structural",
    name: "Custom Porch / Alfresco Under-Roof Area",
    description: "Integrated concrete slab and roofline framing extension for outdoor porch or alfresco entertaining footprint.",
    unitType: "per_m2",
    unitRate: 869,
    isClientSelectable: true,
  },
  {
    id: "str_custom_ds_h2_gf",
    category: "structural",
    name: "Double Storey Ground Floor Living (H2 Inclusions)",
    description: "Ground floor structural living area construction with engineered floor joists above for double storey custom home.",
    unitType: "per_m2",
    unitRate: 1500,
    isClientSelectable: true,
  },
  {
    id: "str_custom_ds_h2_ff",
    category: "structural",
    name: "Double Storey First Floor Living (H2 Inclusions)",
    description: "Upper floor structural living area framing, floor sheeting, insulation, and roofline based on H2 Builder specification.",
    unitType: "per_m2",
    unitRate: 1800,
    isClientSelectable: true,
  },
  {
    id: "str_custom_ds_h3_gf",
    category: "structural",
    name: "Double Storey Ground Floor Living (H3 Inclusions)",
    description: "Ground floor structural living area construction with engineered upper joist framing for double storey custom home (H3 spec).",
    unitType: "per_m2",
    unitRate: 1650,
    isClientSelectable: true,
  },
  {
    id: "str_custom_ds_h3_ff",
    category: "structural",
    name: "Double Storey First Floor Living (H3 Inclusions)",
    description: "Upper floor structural living area framing, premium acoustic floor sheeting, and roofline based on H3 Luxury specification.",
    unitType: "per_m2",
    unitRate: 1950,
    isClientSelectable: true,
  },
  {
    id: "str_balcony_uncovered",
    category: "structural",
    name: "Uncovered Balcony Structure with H2 Range Tiles",
    description: "External cantilevered or post-supported balcony structure, waterproofed and finished with H2 range ceramic floor tiles.",
    unitType: "per_m2",
    unitRate: 2000,
    isClientSelectable: true,
  },
  {
    id: "str_balcony_covered",
    category: "structural",
    name: "Covered Balcony Structure with H2 Range Tiles",
    description: "Covered upper floor balcony structure with extended roofline, ceiling lining, waterproofing, and H2 range floor tiles.",
    unitType: "per_m2",
    unitRate: 2500,
    isClientSelectable: true,
  },
  {
    id: "str_add_gf_ss",
    category: "structural",
    name: "Additional Ground Floor Living Area (Single Storey)",
    description: "Extended ground floor enclosed living area with integrated roof trusses, insulation, and external cladding.",
    unitType: "per_m2",
    unitRate: 1420,
    isClientSelectable: true,
  },
  {
    id: "str_add_gf_ds",
    category: "structural",
    name: "Additional Ground Floor Living Area (Double Storey)",
    description: "Extended ground floor structural footprint with intermediate engineered floor joists and load-bearing framing.",
    unitType: "per_m2",
    unitRate: 1480,
    isClientSelectable: true,
  },
  {
    id: "str_add_ff_ds",
    category: "structural",
    name: "Additional First Floor Living Area (Double Storey)",
    description: "Extended upper floor structural living area including structural joists, wall framing, and roof structure.",
    unitType: "per_m2",
    unitRate: 1780,
    isClientSelectable: true,
  },
  {
    id: "str_add_alfresco",
    category: "structural",
    name: "Additional Alfresco Footprint Area",
    description: "Extended under-roof alfresco slab and roofline for enlarged outdoor entertaining space.",
    unitType: "per_m2",
    unitRate: 869,
    isClientSelectable: true,
  },
  {
    id: "str_add_wet_area_surcharge",
    category: "structural",
    name: "Additional Wet Area Surcharge (Bathroom/Ensuite/Laundry)",
    description: "Specialized waterproofing membrane, sub-floor plumbing rough-in, and sand-cement screed surcharge for enlarged wet areas.",
    unitType: "per_m2",
    unitRate: 242,
    isClientSelectable: true,
  },
  {
    id: "str_alfresco_integral_slab_tiled",
    category: "structural",
    name: "Integral Concrete Slab to Alfresco with Level 1 Floor Tiles",
    description: "Monolithic engineered slab poured integrally with main house foundation and tiled in Level 1 outdoor ceramic tiles.",
    unitType: "per_m2",
    unitRate: 228,
    isClientSelectable: true,
  },
  {
    id: "str_wall_70mm",
    category: "structural",
    name: "Additional 70mm Internal Plasterboard Wall",
    description: "70mm structural timber stud internal partition wall with 10mm plasterboard linings and 3-coat paint finish.",
    unitType: "per_lm",
    unitRate: 193,
    isClientSelectable: true,
  },
  {
    id: "str_wall_90mm",
    category: "structural",
    name: "Additional 90mm Internal Plasterboard Wall",
    description: "90mm heavy-duty timber stud partition wall framing with 10mm plasterboard linings and 3-coat paint finish.",
    unitType: "per_lm",
    unitRate: 240,
    isClientSelectable: true,
  },
  {
    id: "str_ceiling_2590_from_2440",
    category: "structural",
    name: "Upgrade to 2,590mm (8'6\") Ceiling Height (ilo 2,440mm)",
    description: "Height increase to 2,590mm wall framing throughout ($45/m² ceiling framing + $3/m² for 2,340mm internal door heights).",
    unitType: "per_m2",
    unitRate: 48,
    isClientSelectable: true,
  },
  {
    id: "str_ceiling_2740_from_2590",
    category: "structural",
    name: "Upgrade to 2,740mm (9'0\") Ceiling Height (from 2,590mm)",
    description: "Height increase to 2,740mm framing including 2,400mm header heights to external doors and windows.",
    unitType: "per_m2",
    unitRate: 55,
    isClientSelectable: true,
  },
  {
    id: "str_ceiling_2740_from_2440",
    category: "structural",
    name: "Upgrade to 2,740mm (9'0\") Ceiling Height (ilo 2,440mm)",
    description: "Full height increase from standard 2,440mm to 2,740mm framing including 2,400mm door/window header heights.",
    unitType: "per_m2",
    unitRate: 73,
    isClientSelectable: true,
  },
  {
    id: "str_ceiling_3000_from_2740",
    category: "structural",
    name: "Upgrade to 3,000mm (10'0\") Ceiling Height (from 2,740mm)",
    description: "Luxury 3,000mm ceiling framing upgrade from 2,740mm height throughout living areas.",
    unitType: "per_m2",
    unitRate: 35,
    isClientSelectable: true,
  },
  {
    id: "str_ceiling_3000_from_2590",
    category: "structural",
    name: "Upgrade to 3,000mm (10'0\") Ceiling Height (from 2,590mm)",
    description: "Luxury 3,000mm ceiling framing upgrade from 2,590mm including 2,340mm internal doors.",
    unitType: "per_m2",
    unitRate: 73,
    isClientSelectable: true,
  },
  {
    id: "str_ceiling_3000_from_2440",
    category: "structural",
    name: "Upgrade to 3,000mm (10'0\") Ceiling Height (ilo 2,440mm)",
    description: "Full luxury 3,000mm ceiling framing upgrade from standard 2,440mm including 2,340mm internal doors.",
    unitType: "per_m2",
    unitRate: 83,
    isClientSelectable: true,
  },
  {
    id: "str_steel_beam_300pfc",
    category: "structural",
    name: "Structural Steel Beam (Up to 300 PFC)",
    description: "Heavy structural parallel flange channel (PFC) steel beam with engineering connections and crane installation ($483/lm + $1,100 base installation).",
    unitType: "per_lm",
    unitRate: 483,
    isClientSelectable: true,
  },
  {
    id: "str_square_set_ceilings",
    category: "structural",
    name: "Square Set Cornice Finish Throughout",
    description: "Modern architectural square-set plaster joint between walls and ceiling in lieu of standard cove cornice.",
    unitType: "per_m2",
    unitRate: 10,
    isClientSelectable: true,
  },
  {
    id: "str_raised_theatre_platform",
    category: "structural",
    name: "Raised Tiered Platform to Home Theatre",
    description: "Engineered stepped timber platform with acoustic isolation underlay for cinema-style multi-level seating.",
    unitType: "per_m2",
    unitRate: 280,
    isClientSelectable: true,
  },
  {
    id: "str_pool_provisions",
    category: "structural",
    name: "Provisions for Close-to-Dwelling Swimming Pool",
    description: "Deep concrete piering to zone of influence, hard safety cover, and structural engineering to allow future pool excavation adjacent to house.",
    unitType: "fixed",
    unitRate: 5000,
    isClientSelectable: true,
  },
  {
    id: "str_screw_piering_kdrb",
    category: "structural",
    name: "Engineered Screw Piering to Base Slab (KDRB Sites)",
    description: "Heavy-duty helical steel screw piers driven to solid bearing stratum to stabilize foundation on disturbed soil/demolition sites.",
    unitType: "per_m2",
    unitRate: 70,
    isClientSelectable: true,
  },
  {
    id: "str_drop_edge_beam",
    category: "structural",
    name: "Reinforced Drop Edge Beam (DEB)",
    description: "Deepened vertical concrete perimeter footing beam to retain site fill and accommodate natural ground slope across building pad.",
    unitType: "per_lm",
    unitRate: 1050,
    isClientSelectable: true,
  },
  {
    id: "str_roof_gable",
    category: "structural",
    name: "Architectural Roof Gable Feature",
    description: "Pitched decorative gable infill with weatherboard or batten cladding and flashing in lieu of standard hip roofline.",
    unitType: "per_lm",
    unitRate: 200,
    isClientSelectable: true,
  },
  {
    id: "str_elevator_basic",
    category: "structural",
    name: "Provisions for Residential Elevator (Basic Fitout)",
    description: "Structural shaft construction, load-bearing concrete pit, and electrical rough-in for future residential lift installation.",
    unitType: "fixed",
    unitRate: 45000,
    isClientSelectable: true,
  },
  {
    id: "str_elevator_highend",
    category: "structural",
    name: "Provisions for Residential Elevator (High-End Fitout)",
    description: "Architectural glass-ready structural lift shaft, 3-phase high-capacity power circuit, and luxury elevator mechanical installation.",
    unitType: "fixed",
    unitRate: 60000,
    isClientSelectable: true,
  },

  // ==========================================
  // 2. COUNCIL & STATUTORY REQUIREMENTS
  // ==========================================
  {
    id: "counc_town_planner_da_gccc",
    category: "council_statutory",
    name: "Town Planner Development Assessment Report (Gold Coast City Council)",
    description: "Comprehensive Town Planner Development Assessment report including preparation, submission, and coordination of formal Request for Information (RFI) responses for Gold Coast City Council.",
    unitType: "fixed",
    unitRate: 10478,
    isClientSelectable: true,
  },
  {
    id: "counc_gccc_lodgement_fee",
    category: "council_statutory",
    name: "Council Lodgement Fee for Development Assessment (Gold Coast City Council)",
    description: "Statutory municipal development assessment application lodgement and processing fee paid directly to Gold Coast City Council.",
    unitType: "fixed",
    unitRate: 11249,
    isClientSelectable: true,
  },
  {
    id: "counc_traffic_pedestrian_control",
    category: "council_statutory",
    name: "Traffic & Pedestrian Control Plan with Implementation",
    description: "Provisional allowance for a certified Traffic and Pedestrian Control Plan, site set up, safety signage hire, and implementation during construction operations ($5,000 increments).",
    unitType: "fixed",
    unitRate: 5000,
    isClientSelectable: true,
  },
  {
    id: "counc_da_app",
    category: "council_statutory",
    name: "Council Development Application (DA)",
    description: "Town planning statement, planning overlays analysis, statutory fee management, and formal council application lodgement.",
    unitType: "fixed",
    unitRate: 8000,
    isClientSelectable: true,
  },
  {
    id: "counc_infra_dual_living",
    category: "council_statutory",
    name: "Council Infrastructure Charges (Dual Living / Auxiliary Unit)",
    description: "Mandatory local government statutory infrastructure headworks contribution charges for secondary dwelling utility connections.",
    unitType: "fixed",
    unitRate: 22500,
    isClientSelectable: true,
  },
  {
    id: "counc_covenant_standard",
    category: "council_statutory",
    name: "Estate Covenant Compliance Allowance (Standard Lot)",
    description: "Materials, articulated facade detailing, and finish upgrades required to satisfy developer covenant design review panel.",
    unitType: "fixed",
    unitRate: 5000,
    isClientSelectable: true,
  },
  {
    id: "counc_covenant_corner",
    category: "council_statutory",
    name: "Estate Covenant Compliance Allowance (Corner Lot)",
    description: "Dual-frontage articulation, return fence screening, and architectural enhancements required for prominent corner allotments.",
    unitType: "fixed",
    unitRate: 7500,
    isClientSelectable: true,
  },
  {
    id: "counc_setback_relaxation",
    category: "council_statutory",
    name: "Council Boundary Setback Relaxation Application",
    description: "Town planning assessment, site plan drafting, and council referral application for building envelope setback relaxation ($1,500 base + $500 per additional side).",
    unitType: "fixed",
    unitRate: 1500,
    isClientSelectable: true,
  },
  {
    id: "counc_standard_ba_fees",
    category: "council_statutory",
    name: "Standard Building Approval (BA) & Certification Fees",
    description: "Building certifier lodgement, inspection schedule, and council archival fees ($2,500 standard / $0 Brisbane + $400 per kitchen/bathroom).",
    unitType: "fixed",
    unitRate: 2500,
    isClientSelectable: true,
  },
  {
    id: "counc_bos_application",
    category: "council_statutory",
    name: "Build Over Sewer (BOS) Council Application",
    description: "Structural engineering certification, council water authority approval, and formal permit to build adjacent to public sewer main.",
    unitType: "fixed",
    unitRate: 1700,
    isClientSelectable: true,
  },
  {
    id: "counc_traffic_control",
    category: "council_statutory",
    name: "Traffic Control Management Plan & Implementation",
    description: "Council approved traffic management plan, road permit, and certified traffic controllers during heavy concrete and truss deliveries.",
    unitType: "fixed",
    unitRate: 5000,
    isClientSelectable: true,
  },
  {
    id: "counc_id_survey_standard",
    category: "council_statutory",
    name: "Identification Boundary Survey (Missing Pegs)",
    description: "Registered surveyor site cadastral boundary search, corner peg reinstatement, and identification certificate.",
    unitType: "fixed",
    unitRate: 4500,
    isClientSelectable: true,
  },
  {
    id: "counc_id_survey_acreage",
    category: "council_statutory",
    name: "Acreage Boundary Identification Survey",
    description: "Full cadastral boundary identification survey, electronic GPS boundary marking, and pegging for large acreage property.",
    unitType: "fixed",
    unitRate: 6000,
    isClientSelectable: true,
  },

  // ==========================================
  // 3. SITE SPECIFIC & ENGINEERING REPORTS
  // ==========================================
  {
    id: "site_flood_overlay_code_report",
    category: "site_earthworks",
    name: "Site Specific Flood Overlay Code Assessment Report",
    description: "Comprehensive site-specific flood overlay code assessment and hydraulic engineering report to satisfy local government flood planning codes.",
    unitType: "fixed",
    unitRate: 7600,
    isClientSelectable: true,
  },
  {
    id: "site_flood_report",
    category: "site_earthworks",
    name: "Flood Hazard Overlay & Hydrology Engineering Report",
    description: "Hydraulic flood modeling and technical engineering report to determine minimum habitable floor level (RL) above flood level.",
    unitType: "fixed",
    unitRate: 7000,
    isClientSelectable: true,
  },
  {
    id: "site_slab_h1",
    category: "site_earthworks",
    name: "H1 Slab Soil Classification Upgrade",
    description: "Stiffened raft concrete slab with upgraded steel reinforcement mesh to accommodate moderately reactive clay soil movement.",
    unitType: "per_m2",
    unitRate: 30,
    isClientSelectable: true,
  },
  {
    id: "site_slab_h2",
    category: "site_earthworks",
    name: "H2 Slab Soil Classification Upgrade",
    description: "Heavy-duty engineered concrete foundation with deepened internal stiffening beams for highly reactive clay ground.",
    unitType: "per_m2",
    unitRate: 55,
    isClientSelectable: true,
  },
  {
    id: "site_slab_e1",
    category: "site_earthworks",
    name: "E1 Slab Soil Classification Upgrade",
    description: "Specialized ultra-stiff foundation engineering designed for extremely reactive expansive soil profiles.",
    unitType: "per_m2",
    unitRate: 80,
    isClientSelectable: true,
  },
  {
    id: "site_slab_e2",
    category: "site_earthworks",
    name: "E2 Slab Soil Classification Upgrade",
    description: "Maximum foundation stiffness design with dense steel reinforcement cage for severe ground movement conditions.",
    unitType: "per_m2",
    unitRate: 100,
    isClientSelectable: true,
  },
  {
    id: "site_concrete_32mpa_acid",
    category: "site_earthworks",
    name: "32 MPa Chemical-Resistant Concrete (Acid Sulfate Soil RL < 5.0m)",
    description: "High-density 32 MPa concrete mix to protect sub-floor foundation integrity in aggressive low-lying acid sulfate soil conditions.",
    unitType: "per_m2",
    unitRate: 17,
    isClientSelectable: true,
  },
  {
    id: "site_articulated_plumbing",
    category: "site_earthworks",
    name: "Articulated Plumbing Flexible Connections (H, E & P Class)",
    description: "Engineered flexible expansion joints and stainless-steel strapping to prevent plumbing pipe shear in reactive soil movements.",
    unitType: "fixed",
    unitRate: 1884,
    isClientSelectable: true,
  },
  {
    id: "site_wind_n3_ss",
    category: "site_earthworks",
    name: "N3 Wind Rating Construction Package (Single Storey)",
    description: "Upgraded framing tie-down straps, heavy-duty cyclonic brackets, and reinforced window frame assemblies for N3 wind rating.",
    unitType: "fixed",
    unitRate: 2500,
    isClientSelectable: true,
  },
  {
    id: "site_wind_n3_ds",
    category: "site_earthworks",
    name: "N3 Wind Rating Construction Package (Double Storey)",
    description: "Engineered high-uplift tie-downs, threaded cyclone rods, and structural wall bracing panels for double storey N3 exposure.",
    unitType: "fixed",
    unitRate: 3500,
    isClientSelectable: true,
  },
  {
    id: "site_wind_n4_ss",
    category: "site_earthworks",
    name: "N4 High Wind Rating Construction Package (Single Storey)",
    description: "High-wind structural framing, specialized window frames with heavy safety glazing, and extreme anchor tie-downs for N4 exposure.",
    unitType: "fixed",
    unitRate: 4500,
    isClientSelectable: true,
  },
  {
    id: "site_wind_n4_ds",
    category: "site_earthworks",
    name: "N4 High Wind Rating Construction Package (Double Storey)",
    description: "Complete engineered cyclonic tie-down assemblies, heavy shear bracing, and N4-rated window glazing for two levels.",
    unitType: "fixed",
    unitRate: 6500,
    isClientSelectable: true,
  },
  {
    id: "site_bushfire_report",
    category: "site_earthworks",
    name: "Site Specific Bushfire Hazard Assessment Report",
    description: "Qualified bushfire consultant site survey and formal Bushfire Attack Level (BAL) report determining statutory building requirements.",
    unitType: "fixed",
    unitRate: 1500,
    isClientSelectable: true,
  },
  {
    id: "site_bal_12_5_ss",
    category: "site_earthworks",
    name: "Bushfire Protection Upgrade — BAL-12.5 (Single Storey)",
    description: "Ember guards, corrosion-resistant stainless-steel/bronze mesh screens (≤2mm aperture), and fire-rated door perimeter seals.",
    unitType: "fixed",
    unitRate: 6500,
    isClientSelectable: true,
  },
  {
    id: "site_bal_12_5_ds",
    category: "site_earthworks",
    name: "Bushfire Protection Upgrade — BAL-12.5 (Double Storey)",
    description: "Comprehensive ember guards to both levels, weep hole metal mesh, non-combustible flashings, and toughened glazing seals.",
    unitType: "fixed",
    unitRate: 10000,
    isClientSelectable: true,
  },
  {
    id: "site_bal_19_ss",
    category: "site_earthworks",
    name: "Bushfire Protection Upgrade — BAL-19 (Single Storey)",
    description: "5mm toughened safety glass to all external windows and doors, metal fascia shields, and non-combustible external wall seals.",
    unitType: "fixed",
    unitRate: 8000,
    isClientSelectable: true,
  },
  {
    id: "site_bal_19_ds",
    category: "site_earthworks",
    name: "Bushfire Protection Upgrade — BAL-19 (Double Storey)",
    description: "5mm toughened glass throughout both levels, fire-rated external entry doors, metal ember shields, and sub-floor fire sealing.",
    unitType: "fixed",
    unitRate: 12000,
    isClientSelectable: true,
  },
  {
    id: "site_bal_29_ss",
    category: "site_earthworks",
    name: "Bushfire Protection Upgrade — BAL-29 (Single Storey)",
    description: "6mm toughened glass, non-combustible cladding/fascia, fire-rated garage doors with draught seals, and roof sarking.",
    unitType: "fixed",
    unitRate: 10000,
    isClientSelectable: true,
  },
  {
    id: "site_bal_29_ds",
    category: "site_earthworks",
    name: "Bushfire Protection Upgrade — BAL-29 (Double Storey)",
    description: "Full double storey BAL-29 protection with 6mm toughened glass, fire-rated doors, non-combustible cladding, and roof sarking.",
    unitType: "fixed",
    unitRate: 14000,
    isClientSelectable: true,
  },
  {
    id: "site_bal_40_ss",
    category: "site_earthworks",
    name: "Bushfire Protection Upgrade — BAL-40 (Single Storey)",
    description: "Flame-resistant radiant heat barriers, certified metal bushfire shutters/flame-rated glass, and non-combustible building envelope.",
    unitType: "fixed",
    unitRate: 15000,
    isClientSelectable: true,
  },
  {
    id: "site_bal_40_ds",
    category: "site_earthworks",
    name: "Bushfire Protection Upgrade — BAL-40 (Double Storey)",
    description: "Maximum flame-resistant protection for two levels including certified steel fire shutters and extreme heat-shielded assemblies.",
    unitType: "fixed",
    unitRate: 19000,
    isClientSelectable: true,
  },
  {
    id: "site_acoustic_report",
    category: "site_earthworks",
    name: "Acoustic Engineering Assessment & Report",
    description: "Qualified acoustic engineer noise intrusion assessment and report for road, railway, or aircraft transport noise overlays.",
    unitType: "fixed",
    unitRate: 2700,
    isClientSelectable: true,
  },
  {
    id: "site_acoustic_cat1_ss",
    category: "site_earthworks",
    name: "Acoustic Attenuation Package — Category 1 (Single Storey)",
    description: "Acoustic perimeter door/window seals, upgraded glass thickness, and high-density wall insulation batts.",
    unitType: "fixed",
    unitRate: 5000,
    isClientSelectable: true,
  },
  {
    id: "site_acoustic_cat1_ds",
    category: "site_earthworks",
    name: "Acoustic Attenuation Package — Category 1 (Double Storey)",
    description: "Acoustic seals, sound-rated ceiling insulation, and upgraded window glazing for two storeys.",
    unitType: "fixed",
    unitRate: 10000,
    isClientSelectable: true,
  },
  {
    id: "site_acoustic_cat2_ss",
    category: "site_earthworks",
    name: "Acoustic Attenuation Package — Category 2 (Single Storey)",
    description: "Heavy acoustic laminated glazing, double layer sound-rated plasterboard linings, and solid core external doors.",
    unitType: "fixed",
    unitRate: 10000,
    isClientSelectable: true,
  },
  {
    id: "site_acoustic_cat2_ds",
    category: "site_earthworks",
    name: "Acoustic Attenuation Package — Category 2 (Double Storey)",
    description: "Heavy acoustic laminated glass, sound-isolated ceiling resilient mounts, and high-density acoustic wall batts across both levels.",
    unitType: "fixed",
    unitRate: 20000,
    isClientSelectable: true,
  },
  {
    id: "site_acoustic_cat3_ss",
    category: "site_earthworks",
    name: "Acoustic Attenuation Package — Category 3 (Single Storey)",
    description: "Specialized double glazing with wide air gap, staggered acoustic stud framing, and high-transmission acoustic dampeners.",
    unitType: "fixed",
    unitRate: 20000,
    isClientSelectable: true,
  },
  {
    id: "site_acoustic_cat3_ds",
    category: "site_earthworks",
    name: "Acoustic Attenuation Package — Category 3 (Double Storey)",
    description: "Maximum noise attenuation package with decoupled wall assemblies, ultra-heavy acoustic glazing, and sound baffles.",
    unitType: "fixed",
    unitRate: 40000,
    isClientSelectable: true,
  },
  {
    id: "site_stormwater_hydraulic_report",
    category: "site_earthworks",
    name: "Civil Stormwater Hydraulic Engineering Report",
    description: "Civil stormwater design, detention basin sizing, and overland flow path management report for council approval.",
    unitType: "fixed",
    unitRate: 3000,
    isClientSelectable: true,
  },
  {
    id: "site_landslide_report",
    category: "site_earthworks",
    name: "Landslide Overlay & Slope Stability Geotechnical Report",
    description: "Chartered geotechnical engineer slope hazard assessment, core drill soil testing, and foundation stabilization report.",
    unitType: "fixed",
    unitRate: 3000,
    isClientSelectable: true,
  },
  {
    id: "site_arborist_report",
    category: "site_earthworks",
    name: "Certified Arborist Tree Health & Impact Report",
    description: "Tree root protection zone (TPZ) mapping, health assessment, and tree retention/removal report for council submission.",
    unitType: "fixed",
    unitRate: 800,
    isClientSelectable: true,
  },
  {
    id: "site_marine_full",
    category: "site_earthworks",
    name: "Marine Exposure Protection (Full Coastal Exposure)",
    description: "316-grade stainless steel fixings, anti-corrosion flashings, sealed electrical fittings, and marine-grade exterior coating system.",
    unitType: "fixed",
    unitRate: 8000,
    isClientSelectable: true,
  },
  {
    id: "site_marine_moderate",
    category: "site_earthworks",
    name: "Marine Exposure Protection (Moderate Coastal Exposure)",
    description: "Corrosion-resistant exterior fasteners, protective powder-coating to aluminium frames, and moisture-sealed fittings.",
    unitType: "fixed",
    unitRate: 4000,
    isClientSelectable: true,
  },
  {
    id: "site_soil_contour_post_demo",
    category: "site_earthworks",
    name: "Post-Demolition Soil Test & Contour Laser Survey",
    description: "Soil boreholes re-drilling and laser contour survey conducted after existing house demolition to certify true foundation conditions.",
    unitType: "fixed",
    unitRate: 1600,
    isClientSelectable: true,
  },
  {
    id: "site_demolition_ss",
    category: "site_earthworks",
    name: "Single Storey House Demolition & Asbestos Removal",
    description: "Complete dwelling teardown, licensed hazardous asbestos removal, foundation breakout, site clean-up, and waste disposal tipping.",
    unitType: "fixed",
    unitRate: 30000,
    isClientSelectable: true,
  },
  {
    id: "site_demolition_ds",
    category: "site_earthworks",
    name: "Double Storey House Demolition & Asbestos Removal",
    description: "Full two-storey structural teardown, licensed asbestos removal, heavy foundation breakout, and complete site clearance.",
    unitType: "fixed",
    unitRate: 35000,
    isClientSelectable: true,
  },
  {
    id: "site_driveway_demo",
    category: "site_earthworks",
    name: "Existing Concrete Driveway & Paving Demolition",
    description: "Hydraulic breaker jackhammering, concrete slab removal, and off-site recycling of existing driveway and concrete paths.",
    unitType: "fixed",
    unitRate: 10000,
    isClientSelectable: true,
  },
  {
    id: "site_rock_breaker",
    category: "site_earthworks",
    name: "Rock Breaker Allowance (Sub-surface Rock Excavation)",
    description: "Excavator hydraulic rock hammer attachment hire and operator labor to excavate solid sub-surface rock on site.",
    unitType: "fixed",
    unitRate: 10000,
    isClientSelectable: true,
  },
  {
    id: "site_services_lead_in",
    category: "site_earthworks",
    name: "Additional Services Lead-In Run (Power, Water, NBN above 10m)",
    description: "Underground trenching, conduit, electrical mains wiring, water pipe, and NBN lead-in pathway beyond standard 10-meter allowance.",
    unitType: "per_lm",
    unitRate: 70,
    isClientSelectable: true,
  },
  {
    id: "site_sewer_point_investigation",
    category: "site_earthworks",
    name: "Sewer Connection Point Physical Investigation",
    description: "On-site utility locator search, depth verification, and physical excavation when council as-constructed plans are missing.",
    unitType: "fixed",
    unitRate: 4700,
    isClientSelectable: true,
  },
  {
    id: "site_potholing_vacuum",
    category: "site_earthworks",
    name: "Hydro-Vacuum Potholing (Sewer / Stormwater)",
    description: "Non-destructive high-pressure water vacuum excavation to locate and safely expose existing underground utility mains.",
    unitType: "fixed",
    unitRate: 4500,
    isClientSelectable: true,
  },
  {
    id: "site_cctv_pipe_inspection",
    category: "site_earthworks",
    name: "CCTV Sewer Pipe Camera Inspection & Report",
    description: "High-definition motorized tractor camera inspection through existing sewer main to verify line integrity and condition.",
    unitType: "fixed",
    unitRate: 2500,
    isClientSelectable: true,
  },
  {
    id: "site_hstp_plant",
    category: "site_earthworks",
    name: "Home Sewerage Treatment Plant (HSTP) Supply & Install",
    description: "Complete aerated wastewater treatment system, air blower, control panel, submersible pump, and sub-surface irrigation trenches.",
    unitType: "fixed",
    unitRate: 25000,
    isClientSelectable: true,
  },
  {
    id: "site_charged_downpipes",
    category: "site_earthworks",
    name: "Charged Stormwater Downpipe System",
    description: "Underground sealed high-pressure stormwater drainage pipe system to discharge water when standard gravity rubble pit is unfeasible.",
    unitType: "fixed",
    unitRate: 12000,
    isClientSelectable: true,
  },
  {
    id: "site_property_power_pole",
    category: "site_earthworks",
    name: "Private Property Power Pole (Overhead to Underground)",
    description: "Treated timber or galvanized steel property power pole with meter enclosure converting overhead street power to underground lead-in.",
    unitType: "fixed",
    unitRate: 4200,
    isClientSelectable: true,
  },
  {
    id: "site_travel_allowance",
    category: "site_earthworks",
    name: "Out of Service Area Travel Allowance",
    description: "Mobilization, accommodation, and trade logistics allowance for building outside the standard metropolitan service zone.",
    unitType: "fixed",
    unitRate: 0,
    isClientSelectable: true,
  },
  {
    id: "site_contingency_allowance",
    category: "site_earthworks",
    name: "Contingency Allowance for Unknown Site Conditions",
    description: "Dedicated client safety buffer allowance for unknown underground conditions, tree roots, or unexpected council conditions ($5k-$15k).",
    unitType: "fixed",
    unitRate: 5000,
    isClientSelectable: true,
  },

  // ==========================================
  // 4. DOORS & WINDOWS
  // ==========================================
  {
    id: "dw_cornerless_stacker_ss",
    category: "doors_windows",
    name: "Cornerless Stacker Sliding Doors to Alfresco (Single Storey)",
    description: "Dual aluminium multi-panel stacker sliding doors opening to seamless 90° corner without fixed post, including engineered overhead lintel.",
    unitType: "fixed",
    unitRate: 4000,
    isClientSelectable: true,
  },
  {
    id: "dw_cornerless_stacker_ds",
    category: "doors_windows",
    name: "Cornerless Stacker Sliding Doors to Alfresco (Double Storey)",
    description: "Heavy-duty 90° zero-corner stacker doors with engineered structural steel overhead beam support for upper level loads.",
    unitType: "fixed",
    unitRate: 5000,
    isClientSelectable: true,
  },
  {
    id: "dw_sliding_door_2124",
    category: "doors_windows",
    name: "21-24 Aluminium Framed Sliding Door (2,100h x 2,400w)",
    description: "2,100mm high x 2,400mm wide powder-coated aluminium glass sliding door with key lock and safety glazing.",
    unitType: "fixed",
    unitRate: 1594,
    isClientSelectable: true,
  },
  {
    id: "dw_window_1809",
    category: "doors_windows",
    name: "18-09 Aluminium Framed Window (1,800h x 900w)",
    description: "1,800mm high x 900mm wide powder-coated aluminium opening window with key lock and insect screen.",
    unitType: "fixed",
    unitRate: 490,
    isClientSelectable: true,
  },
  {
    id: "dw_corner_window",
    category: "doors_windows",
    name: "Architectural Butt-Jointed Fixed Corner Window",
    description: "Feature 90-degree butt-jointed corner glass window providing unobstructed panoramic views.",
    unitType: "fixed",
    unitRate: 1800,
    isClientSelectable: true,
  },
  {
    id: "dw_cavity_sliding_door",
    category: "doors_windows",
    name: "Cavity Sliding Door Unit (2,340mm x 870mm)",
    description: "Flush-mounting internal timber door frame sliding smoothly into wall cavity with recessed flush pull hardware.",
    unitType: "fixed",
    unitRate: 880,
    isClientSelectable: true,
  },
  {
    id: "dw_entry_door_1020",
    category: "doors_windows",
    name: "1,020mm Wide Front Entry Door (ilo Standard)",
    description: "Upgraded 1,020mm wide solid core painted/stained front entry door with weather seal and quality lockset.",
    unitType: "fixed",
    unitRate: 793,
    isClientSelectable: true,
  },
  {
    id: "dw_entry_door_2340_1200",
    category: "doors_windows",
    name: "Grand 2,340mm x 1,200mm Architectural Entry Door",
    description: "Grand 2,340mm x 1,200mm wide architectural entrance door with translucent glass inserts and pull handle.",
    unitType: "fixed",
    unitRate: 1350,
    isClientSelectable: true,
  },
  {
    id: "dw_security_screen_door",
    category: "doors_windows",
    name: "Diamond Barrier Security Screen Door (Per Hinged Door)",
    description: "Heavy-duty extruded aluminium security grille screen door with 3-point deadbolt lock and insect mesh.",
    unitType: "fixed",
    unitRate: 998,
    isClientSelectable: true,
  },
  {
    id: "dw_security_screen_window",
    category: "doors_windows",
    name: "Diamond Barrier Security Screen (Per Window)",
    description: "Powder-coated aluminium security grille screen fitted securely to opening window.",
    unitType: "fixed",
    unitRate: 572,
    isClientSelectable: true,
  },

  // ==========================================
  // 5. INTERNAL - KITCHEN & APPLIANCES
  // ==========================================
  {
    id: "kit_fp_cooktop_600_electric",
    category: "internal_kitchen",
    name: "Fisher & Paykel 600mm Black Glass Electric Cooktop (CE604LBX2)",
    description: "Fisher & Paykel 600mm 4-zone black ceramic glass electric cooktop (CE604LBX2) with touch controls and flat easy-clean surface.",
    unitType: "fixed",
    unitRate: 1263,
    isClientSelectable: true,
  },
  {
    id: "kit_fp_rangehood_600_slideout",
    category: "internal_kitchen",
    name: "Fisher & Paykel 600mm Slide-Out Rangehood (HS60LRX4)",
    description: "Fisher & Paykel 600mm stainless steel slide-out rangehood (HS60LRX4) with dual multi-layer filters and ducted exhaust.",
    unitType: "fixed",
    unitRate: 713,
    isClientSelectable: true,
  },
  {
    id: "kit_900_appliances_h2",
    category: "internal_kitchen",
    name: "900mm H2 Kitchen Appliances Upgrade (ilo H1 600mm)",
    description: "Upgrade from 600mm to premium 900mm stainless steel gas/electric cooktop, canopy rangehood, and 900mm built-in oven.",
    unitType: "fixed",
    unitRate: 2787,
    isClientSelectable: true,
  },
  {
    id: "kit_extra_600_oven",
    category: "internal_kitchen",
    name: "Additional 600mm Stainless Steel Wall Oven",
    description: "Second built-in 600mm multi-function electric oven with dedicated power circuit and custom joinery tower installation.",
    unitType: "fixed",
    unitRate: 1500,
    isClientSelectable: true,
  },
  {
    id: "kit_integrated_fridge",
    category: "internal_kitchen",
    name: "Integrated Luxury Refrigerator Cabinetry Fitout",
    description: "Custom seamless joinery cabinetry housing and ventilation channels to integrate client's built-in refrigerator.",
    unitType: "fixed",
    unitRate: 10000,
    isClientSelectable: true,
  },
  {
    id: "kit_base_cupboards_20mm_stone",
    category: "internal_kitchen",
    name: "600mm Base Cupboards with 20mm Category 1 Stone Top",
    description: "600mm deep laminate base cabinetry with soft-close drawers and 20mm thick Category 1 engineered stone benchtop.",
    unitType: "per_lm",
    unitRate: 1188,
    isClientSelectable: true,
  },
  {
    id: "kit_overhead_cupboards",
    category: "internal_kitchen",
    name: "Overhead Kitchen / Laundry Cupboards",
    description: "Laminate overhead cabinets with concealed magnetic catches and adjustable interior shelving.",
    unitType: "per_lm",
    unitRate: 850,
    isClientSelectable: true,
  },
  {
    id: "kit_stone_upgrade_ilo_laminate",
    category: "internal_kitchen",
    name: "20mm Category 1 Stone Benchtop (ilo Laminate)",
    description: "Upgrade kitchen benchtops from standard laminate to 20mm polished Category 1 engineered stone.",
    unitType: "per_lm",
    unitRate: 400,
    isClientSelectable: true,
  },
  {
    id: "kit_stone_complete_20mm",
    category: "internal_kitchen",
    name: "20mm Category 1 Stone Benchtop Surface (Complete)",
    description: "Supply and installation of 20mm Category 1 engineered quartz stone benchtop with polished arrised edge profile.",
    unitType: "per_lm",
    unitRate: 780,
    isClientSelectable: true,
  },
  {
    id: "kit_stone_40mm_upgrade",
    category: "internal_kitchen",
    name: "Upgrade Stone Benchtop Thickness to 40mm (ilo 20mm)",
    description: "Enhanced 40mm laminated edge profile to all kitchen island and benchtop perimeters.",
    unitType: "per_lm",
    unitRate: 245,
    isClientSelectable: true,
  },
  {
    id: "kit_extend_island_bench",
    category: "internal_kitchen",
    name: "Extend H2 Kitchen Island Bench Footprint",
    description: "Additional length of island bench cabinetry with matching 20mm stone top and breakfast bar overhang.",
    unitType: "per_lm",
    unitRate: 1322,
    isClientSelectable: true,
  },
  {
    id: "kit_clark_polar_undermount_sink",
    category: "internal_kitchen",
    name: "Clark Polar Double Bowl Undermount Sink (PPL20BU)",
    description: "Premium 304-grade stainless steel undermount double bowl sink seamlessly fitted into stone island bench (ilo standard).",
    unitType: "fixed",
    unitRate: 421,
    isClientSelectable: true,
  },
  {
    id: "kit_fp_cooktop_900",
    category: "internal_kitchen",
    name: "Additional 900mm Fisher & Paykel Gas Cooktop (H2)",
    description: "Additional 900mm Fisher & Paykel 5-burner stainless steel gas cooktop for scullery or secondary kitchen.",
    unitType: "fixed",
    unitRate: 2350,
    isClientSelectable: true,
  },
  {
    id: "kit_fp_rangehood_900",
    category: "internal_kitchen",
    name: "Additional 900mm Fisher & Paykel Rangehood (H2)",
    description: "Additional 900mm Fisher & Paykel high-extraction ducted canopy rangehood.",
    unitType: "fixed",
    unitRate: 900,
    isClientSelectable: true,
  },

  // ==========================================
  // 6. INTERNAL - BATHROOM & ENSUITE
  // ==========================================
  {
    id: "bath_additional_ensuite",
    category: "internal_bathroom",
    name: "Complete Additional Ensuite Bathroom (H2 Builders Range)",
    description: "Fully tiled bathroom containing walk-in semi-frameless shower, single vanity with mixer tap, toilet suite, and exhaust fan.",
    unitType: "fixed",
    unitRate: 10000,
    isClientSelectable: true,
  },
  {
    id: "bath_ftc_tiles_main",
    category: "internal_bathroom",
    name: "Floor-to-Ceiling Wall Tiles — Main Bathroom",
    description: "Full-height ceramic wall tiling throughout main bathroom up to ceiling line with polished metal angle trim.",
    unitType: "fixed",
    unitRate: 2500,
    isClientSelectable: true,
  },
  {
    id: "bath_ftc_tiles_ensuite",
    category: "internal_bathroom",
    name: "Floor-to-Ceiling Wall Tiles — Master Ensuite",
    description: "Full-height luxury ceramic wall tiling throughout master ensuite up to ceiling line with polished metal trim.",
    unitType: "fixed",
    unitRate: 2500,
    isClientSelectable: true,
  },
  {
    id: "bath_heat_pump_extra_ensuite",
    category: "internal_bathroom",
    name: "Additional Heat Pump Hot Water System (Extra Ensuite)",
    description: "Energy-efficient 270L external heat pump hot water system to support additional wet area plumbing demand.",
    unitType: "fixed",
    unitRate: 3300,
    isClientSelectable: true,
  },

  // ==========================================
  // 7. INTERNAL - BEDROOMS & STORAGE
  // ==========================================
  {
    id: "bed_wir_melamine_shelf_rail",
    category: "internal_bedrooms",
    name: "Walk-In Robe (WIR) Melamine Shelving & Hanging Rail",
    description: "Additional 16mm white melamine open shelving module with full-width oval hanging rail for walk-in wardrobe.",
    unitType: "per_lm",
    unitRate: 100,
    isClientSelectable: true,
  },
  {
    id: "bed_robe_vinyl_sliding",
    category: "internal_bedrooms",
    name: "Built-In Wardrobe with Vinyl Sliding Doors",
    description: "Extended length wardrobe fitout with smooth-gliding vinyl sliding doors, top shelf, and chrome hanging rail.",
    unitType: "per_lm",
    unitRate: 430,
    isClientSelectable: true,
  },
  {
    id: "bed_robe_mirror_sliding",
    category: "internal_bedrooms",
    name: "Built-In Wardrobe with Mirrored Sliding Doors",
    description: "Extended length wardrobe fitout with full-height safety mirror sliding doors, top shelf, and chrome hanging rail.",
    unitType: "per_lm",
    unitRate: 530,
    isClientSelectable: true,
  },
  {
    id: "bed_melamine_shelving",
    category: "internal_bedrooms",
    name: "Additional White Melamine Storage Shelving",
    description: "Additional 16mm white moisture-resistant melamine shelf installed with support brackets to linen or pantry.",
    unitType: "per_lm",
    unitRate: 62,
    isClientSelectable: true,
  },

  // ==========================================
  // 8. ELECTRICAL, HVAC & SOLAR
  // ==========================================
  {
    id: "elec_3phase_power",
    category: "colour_upgrades",
    name: "Upgrade to 3-Phase Electrical Power Supply",
    description: "3-phase power lead-in and main switchboard upgrade for heavy electrical appliances and rapid EV charging capacity.",
    unitType: "fixed",
    unitRate: 1070,
    isClientSelectable: true,
  },
  {
    id: "elec_ev_charger_circuit",
    category: "colour_upgrades",
    name: "Dedicated 20-Amp EV Charger Circuit to Garage",
    description: "Dedicated high-capacity 20A GPO power circuit wired from main switchboard to garage for electric vehicle charger.",
    unitType: "fixed",
    unitRate: 588,
    isClientSelectable: true,
  },
  {
    id: "hvac_ducted_aircon",
    category: "colour_upgrades",
    name: "Ducted Reverse-Cycle Air Conditioning (ilo H1 Split System)",
    description: "Whole-home multi-zone ducted reverse cycle inverter air conditioning system with digital programmable wall controller.",
    unitType: "fixed",
    unitRate: 12500,
    isClientSelectable: true,
  },
  {
    id: "hvac_airtouch5_wifi",
    category: "colour_upgrades",
    name: "Polyair AirTouch 5 Smart Wi-Fi Controller",
    description: "Touchscreen wall tablet and smartphone app controller with individual zone temperature control sensors.",
    unitType: "fixed",
    unitRate: 1207,
    isClientSelectable: true,
  },
  {
    id: "solar_6_6kw_battery",
    category: "colour_upgrades",
    name: "6.6kW Solar PV System with 5kW Inverter & Home Battery",
    description: "15 Tier-1 monocrystalline solar panels (6.6kW), 5kW hybrid inverter, and integrated home energy battery storage unit.",
    unitType: "fixed",
    unitRate: 12000,
    isClientSelectable: true,
  },
  {
    id: "solar_delete_credit_h3",
    category: "colour_upgrades",
    name: "Credit: Delete Standard Solar System (from H3 Inclusions)",
    description: "Cost reduction credit for removing builder standard 3.3kW solar panel system.",
    unitType: "fixed",
    unitRate: -2300,
    isClientSelectable: true,
  },
  {
    id: "elec_spectrum_studio_allowance",
    category: "colour_upgrades",
    name: "Allowance for Spectrum Colour Studio & Electrical Upgrades",
    description: "Client selection budget allowance for custom electrical fittings, feature pendant lighting, and interior finishes ($2,500 intervals).",
    unitType: "fixed",
    unitRate: 2500,
    isClientSelectable: true,
  },

  // ==========================================
  // 9. EXTERNAL FINISHES & LANDSCAPING
  // ==========================================
  {
    id: "ext_epoxy_garage_floor",
    category: "external",
    name: "Epoxy Flake Floor Coating to Garage",
    description: "Heavy-duty industrial 2-part epoxy resin floor coating with decorative vinyl colour flakes and clear non-slip topcoat.",
    unitType: "per_m2",
    unitRate: 67,
    isClientSelectable: true,
  },
  {
    id: "ext_painted_acrylic_render",
    category: "external",
    name: "Dulux Painted Textured Acrylic Render",
    description: "Multi-coat exterior masonry render and tinted Dulux Weathershield paint application.",
    unitType: "per_m2",
    unitRate: 105,
    isClientSelectable: true,
  },
  {
    id: "ext_driveway_exposed_agg_6m",
    category: "external",
    name: "Exposed Aggregate Concrete Driveway (Up to 6m Setback)",
    description: "Steel mesh reinforced exposed aggregate decorative concrete driveway up to 6-meter building setback.",
    unitType: "fixed",
    unitRate: 11400,
    isClientSelectable: true,
  },
  {
    id: "ext_driveway_exposed_agg_sqm",
    category: "external",
    name: "Exposed Aggregate Concrete Paving (Per m²)",
    description: "Reinforced 100mm thick exposed aggregate decorative concrete slab including excavation, sub-base, and sealing.",
    unitType: "per_m2",
    unitRate: 186,
    isClientSelectable: true,
  },
  {
    id: "ext_turf_supply_install",
    category: "external",
    name: "Premium Turf Supply & Installation (Per m²)",
    description: "Soil preparation, topsoil leveling, and supply/laying of premium drought-tolerant turf (e.g. Wintergreen / Sir Walter).",
    unitType: "per_m2",
    unitRate: 56,
    isClientSelectable: true,
  },
];
